import { Semiconductor } from "@/types";
import { mock_50 } from "./more/mock_50";
import { mock_200 } from "./more/mock_200";
import { mock_500 } from "./more/mock_500";
export const system_composition_index: Semiconductor[] = [
  ...mock_500,
  ...mock_200,
  ...mock_50,
  {
    model_name: "TitanEdge V2",
    type: "controller",
    material: ["gallium-nitride", "silicon"],
    processing_power: 1.9,
    cost_to_produce: 8.2,
    extra: 3,
    life_span_years: 5,
    release_date: "2022-03-27",
    volume_size_cm3: 1.7,
  },
  {
    model_name: "PulseDrive ZX",
    type: "sensor",
    material: ["indium-phosphide"],
    processing_power: 2.1,
    cost_to_produce: 12.0,
    extra: 4,
    life_span_years: 4,
    release_date: "2023-12-01",
    volume_size_cm3: 1.9,
  },
  {
    model_name: "NovaCore A1",
    type: "sensor",
    material: ["germanium", "inp"],
    processing_power: 4.6,
    cost_to_produce: 11.95,
    life_span_years: 4,
    release_date: "2025-11-22",
    volume_size_cm3: 2.69,
  },
  {
    model_name: "NovaNode Prime",
    type: "fpga",
    material: ["inp", "gan"],
    processing_power: 1.12,
    cost_to_produce: 8.36,
    life_span_years: 8,
    release_date: "2013-03-08",
    volume_size_cm3: 0.99,
  },
  {
    model_name: "NeuroCore L2",
    type: "ai-accelerator",
    material: ["silicon-carbide", "gallium-nitride"],
    processing_power: 5.2,
    cost_to_produce: 22.0,
    extra: 5,
    life_span_years: 9,
    release_date: "2023-03-30",
    volume_size_cm3: 3.9,
  },
  {
    model_name: "PhotonEdge Z5",
    type: "sensor",
    material: ["indium-gallium-arsenide", "silicon"],
    processing_power: 2.7,
    cost_to_produce: 11.3,
    extra: 2,
    life_span_years: 5,
    release_date: "2020-06-21",
    volume_size_cm3: 2.2,
  },
  {
    model_name: "CryoChip M8",
    type: "fpga",
    material: ["silicon", "gallium-oxide"],
    processing_power: 3.9,
    cost_to_produce: 16.4,
    extra: 4,
    life_span_years: 7,
    release_date: "2024-01-10",
    volume_size_cm3: 3.0,
  },
  {
    model_name: "NovaCore V9",
    type: "gpu",
    material: ["silicon-carbide", "gallium-arsenide"],
    processing_power: 4.2,
    cost_to_produce: 17.35,
    extra: 2,
    life_span_years: 7,
    release_date: "2022-11-04",
    volume_size_cm3: 3.1,
  },
  {
    model_name: "Quantix Q5",
    type: "controller",
    material: ["indium-phosphide", "silicon"],
    processing_power: 2.8,
    cost_to_produce: 10.25,
    extra: 3,
    life_span_years: 5,
    release_date: "2020-04-17",
    volume_size_cm3: 2.3,
  },
  {
    model_name: "AetherLink T2",
    type: "sensor",
    material: ["gallium-nitride", "silicon"],
    processing_power: 1.9,
    cost_to_produce: 8.4,
    extra: 1,
    life_span_years: 4,
    release_date: "2019-09-22",
    volume_size_cm3: 1.5,
  },
  {
    model_name: "CryoFlux GX",
    type: "fpga",
    material: ["silicon", "germanium"],
    processing_power: 3.3,
    cost_to_produce: 12.75,
    extra: 2,
    life_span_years: 6,
    release_date: "2023-03-15",
    volume_size_cm3: 2.9,
  },
  {
    model_name: "OrionEdge M4",
    type: "cpu",
    material: ["silicon", "gallium-nitride"],
    processing_power: 4.0,
    cost_to_produce: 16.2,
    extra: 2,
    life_span_years: 7,
    release_date: "2024-01-10",
    volume_size_cm3: 2.6,
  },
];
