import { Semiconductor } from "@/types";

export const mock_100: Semiconductor[] = [
  {
    model_name: "AXZ-802",
    type: "gpu",
    material: ["indium-phosphide"],
    processing_power: 2.67,
    cost_to_produce: 28.78,
    extra: 3,
    life_span_years: 2,
    release_date: "2011-11-01",
    volume_size_cm3: 2.02,
  },
  {
    model_name: "RSF-452",
    type: "fpga",
    material: ["silicon-carbide", "gallium-arsenide", "silicon"],
    processing_power: 1.72,
    cost_to_produce: 8.65,
    extra: 3,
    life_span_years: 14,
    release_date: "2024-08-23",
    volume_size_cm3: 7.73,
  },
  {
    model_name: "OUF-864",
    type: "sensor",
    material: ["silicon-carbide", "indium-phosphide", "gan"],
    processing_power: 5.65,
    cost_to_produce: 13.66,
    extra: 5,
    life_span_years: 9,
    release_date: "2011-08-16",
    volume_size_cm3: 1.2,
  },
  {
    model_name: "GQL-882",
    type: "cpu",
    material: ["gallium-arsenide", "indium-gallium-arsenide", "silicon"],
    processing_power: 7.12,
    cost_to_produce: 22.36,
    extra: 2,
    life_span_years: 1,
    release_date: "2006-12-06",
    volume_size_cm3: 9.86,
  },
  {
    model_name: "GPT-561",
    type: "sensor",
    material: [
      "indium-gallium-arsenide",
      "indium-phosphide",
      "silicon-carbide",
    ],
    processing_power: 0.88,
    cost_to_produce: 28.54,
    extra: 3,
    life_span_years: 5,
    release_date: "2005-06-05",
    volume_size_cm3: 9.54,
  },
  {
    model_name: "CUX-219",
    type: "gpu",
    material: ["indium-gallium-arsenide", "indium-phosphide", "sige"],
    processing_power: 3.35,
    cost_to_produce: 16.94,
    extra: 2,
    life_span_years: 1,
    release_date: "2018-03-22",
    volume_size_cm3: 0.0,
  },
  {
    model_name: "ONJ-039",
    type: "controller",
    material: ["inp"],
    processing_power: 0.38,
    cost_to_produce: 26.94,
    extra: 2,
    life_span_years: 1,
    release_date: "2015-11-19",
    volume_size_cm3: 5.0,
  },
  {
    model_name: "HKV-421",
    type: "cpu",
    material: ["silicon-carbide", "indium-gallium-arsenide"],
    processing_power: 8.28,
    cost_to_produce: 11.03,
    extra: 2,
    life_span_years: 6,
    release_date: "2002-11-24",
    volume_size_cm3: 6.46,
  },
  {
    model_name: "WEV-303",
    type: "fpga",
    material: ["silicon-germanium", "inp"],
    processing_power: 8.82,
    cost_to_produce: 12.57,
    extra: 3,
    life_span_years: 6,
    release_date: "2008-07-23",
    volume_size_cm3: 5.03,
  },
  {
    model_name: "RKF-171",
    type: "fpga",
    material: ["gan"],
    processing_power: 4.84,
    cost_to_produce: 19.76,
    extra: 3,
    life_span_years: 4,
    release_date: "2019-11-20",
    volume_size_cm3: 7.36,
  },
  {
    model_name: "SBE-125",
    type: "gpu",
    material: ["gan", "silicon-germanium", "indium-phosphide"],
    processing_power: 3.47,
    cost_to_produce: 13.18,
    extra: 2,
    life_span_years: 8,
    release_date: "2003-06-03",
    volume_size_cm3: 8.83,
  },
  {
    model_name: "LHW-774",
    type: "gpu",
    material: ["gallium-arsenide"],
    processing_power: 2.39,
    cost_to_produce: 11.87,
    extra: 2,
    life_span_years: 13,
    release_date: "2018-05-27",
    volume_size_cm3: 9.42,
  },
  {
    model_name: "FYC-078",
    type: "gpu",
    material: ["indium-gallium-arsenide", "silicon-germanium"],
    processing_power: 6.7,
    cost_to_produce: 27.62,
    extra: 3,
    life_span_years: 7,
    release_date: "2022-10-09",
    volume_size_cm3: 2.98,
  },
  {
    model_name: "XQX-380",
    type: "controller",
    material: ["gan", "germanium", "gallium-nitride"],
    processing_power: 1.36,
    cost_to_produce: 21.24,
    extra: 4,
    life_span_years: 8,
    release_date: "2009-06-29",
    volume_size_cm3: 5.27,
  },
  {
    model_name: "DQT-583",
    type: "gpu",
    material: ["indium-gallium-arsenide"],
    processing_power: 9.28,
    cost_to_produce: 25.06,
    extra: 2,
    life_span_years: 12,
    release_date: "2021-11-09",
    volume_size_cm3: 1.24,
  },
  {
    model_name: "PWR-651",
    type: "sensor",
    material: ["germanium"],
    processing_power: 7.51,
    cost_to_produce: 8.01,
    extra: 1,
    life_span_years: 15,
    release_date: "2014-01-26",
    volume_size_cm3: 1.14,
  },
  {
    model_name: "NFL-295",
    type: "controller",
    material: ["gaas", "gallium-arsenide"],
    processing_power: 3.39,
    cost_to_produce: 24.34,
    extra: 2,
    life_span_years: 12,
    release_date: "2022-04-12",
    volume_size_cm3: 9.9,
  },
  {
    model_name: "PUH-029",
    type: "ai-accelerator",
    material: ["sige", "gallium-arsenide"],
    processing_power: 3.23,
    cost_to_produce: 26.25,
    extra: 1,
    life_span_years: 4,
    release_date: "1996-05-27",
    volume_size_cm3: 3.88,
  },
  {
    model_name: "DNP-528",
    type: "cpu",
    material: ["gallium-arsenide", "indium-gallium-arsenide", "gan"],
    processing_power: 0.33,
    cost_to_produce: 20.55,
    extra: 1,
    life_span_years: 5,
    release_date: "2016-12-06",
    volume_size_cm3: 7.71,
  },
  {
    model_name: "FHO-294",
    type: "ai-accelerator",
    material: ["gan", "inp", "sige"],
    processing_power: 7.86,
    cost_to_produce: 16.62,
    extra: 2,
    life_span_years: 2,
    release_date: "2013-03-13",
    volume_size_cm3: 4.95,
  },
  {
    model_name: "CTN-156",
    type: "controller",
    material: ["gaas", "silicon"],
    processing_power: 1.0,
    cost_to_produce: 27.39,
    extra: 2,
    life_span_years: 14,
    release_date: "2025-12-19",
    volume_size_cm3: 5.37,
  },
  {
    model_name: "FAL-109",
    type: "sensor",
    material: ["indium-gallium-arsenide", "indium-phosphide"],
    processing_power: 6.76,
    cost_to_produce: 8.17,
    extra: 1,
    life_span_years: 3,
    release_date: "2025-08-30",
    volume_size_cm3: 6.52,
  },
  {
    model_name: "DZO-610",
    type: "ai-accelerator",
    material: ["gan"],
    processing_power: 4.03,
    cost_to_produce: 16.15,
    extra: 1,
    life_span_years: 0,
    release_date: "1996-07-03",
    volume_size_cm3: 4.89,
  },
  {
    model_name: "VOE-430",
    type: "cpu",
    material: ["gallium-arsenide", "indium-phosphide", "sige"],
    processing_power: 2.8,
    cost_to_produce: 12.86,
    extra: 2,
    life_span_years: 11,
    release_date: "2001-09-27",
    volume_size_cm3: 8.77,
  },
  {
    model_name: "FXB-620",
    type: "fpga",
    material: ["gan"],
    processing_power: 4.39,
    cost_to_produce: 9.65,
    extra: 1,
    life_span_years: 0,
    release_date: "2000-04-01",
    volume_size_cm3: 7.84,
  },
  {
    model_name: "MPI-092",
    type: "controller",
    material: ["silicon-germanium", "indium-gallium-arsenide", "silicon"],
    processing_power: 2.02,
    cost_to_produce: 29.86,
    extra: 3,
    life_span_years: 9,
    release_date: "2018-12-17",
    volume_size_cm3: 9.33,
  },
  {
    model_name: "NRB-660",
    type: "ai-accelerator",
    material: ["germanium", "indium-gallium-arsenide"],
    processing_power: 1.86,
    cost_to_produce: 8.4,
    extra: 2,
    life_span_years: 1,
    release_date: "2025-11-07",
    volume_size_cm3: 3.38,
  },
  {
    model_name: "ZFG-301",
    type: "controller",
    material: ["silicon-carbide", "gan", "silicon-germanium"],
    processing_power: 8.67,
    cost_to_produce: 27.6,
    extra: 3,
    life_span_years: 7,
    release_date: "1996-12-08",
    volume_size_cm3: 0.24,
  },
  {
    model_name: "YRA-069",
    type: "ai-accelerator",
    material: ["inp"],
    processing_power: 4.61,
    cost_to_produce: 29.24,
    extra: 5,
    life_span_years: 10,
    release_date: "2022-07-26",
    volume_size_cm3: 1.49,
  },
  {
    model_name: "EXJ-651",
    type: "gpu",
    material: ["inp"],
    processing_power: 9.96,
    cost_to_produce: 8.89,
    extra: 5,
    life_span_years: 4,
    release_date: "2015-12-02",
    volume_size_cm3: 3.6,
  },
  {
    model_name: "HHY-358",
    type: "fpga",
    material: ["silicon-germanium", "gallium-arsenide"],
    processing_power: 4.48,
    cost_to_produce: 27.19,
    extra: 1,
    life_span_years: 13,
    release_date: "2007-08-26",
    volume_size_cm3: 1.1,
  },
  {
    model_name: "TGC-843",
    type: "ai-accelerator",
    material: ["silicon-germanium", "gallium-nitride"],
    processing_power: 7.62,
    cost_to_produce: 5.53,
    extra: 4,
    life_span_years: 2,
    release_date: "2014-11-10",
    volume_size_cm3: 7.67,
  },
  {
    model_name: "PWE-871",
    type: "controller",
    material: ["indium-gallium-arsenide", "germanium", "indium-phosphide"],
    processing_power: 9.68,
    cost_to_produce: 22.12,
    extra: 2,
    life_span_years: 8,
    release_date: "2009-07-10",
    volume_size_cm3: 4.85,
  },
  {
    model_name: "FPL-871",
    type: "fpga",
    material: ["gaas"],
    processing_power: 3.14,
    cost_to_produce: 29.56,
    extra: 2,
    life_span_years: 5,
    release_date: "1998-05-07",
    volume_size_cm3: 3.84,
  },
  {
    model_name: "YJJ-037",
    type: "gpu",
    material: ["germanium", "silicon-carbide"],
    processing_power: 6.49,
    cost_to_produce: 17.49,
    extra: 2,
    life_span_years: 3,
    release_date: "2023-05-03",
    volume_size_cm3: 1.1,
  },
  {
    model_name: "MYG-740",
    type: "controller",
    material: ["sige"],
    processing_power: 1.67,
    cost_to_produce: 14.09,
    extra: 3,
    life_span_years: 7,
    release_date: "2004-12-23",
    volume_size_cm3: 8.97,
  },
  {
    model_name: "IFW-459",
    type: "sensor",
    material: ["germanium", "indium-gallium-arsenide", "inp"],
    processing_power: 7.91,
    cost_to_produce: 29.67,
    extra: 1,
    life_span_years: 13,
    release_date: "2023-11-01",
    volume_size_cm3: 4.5,
  },
  {
    model_name: "BQK-397",
    type: "sensor",
    material: ["indium-phosphide", "silicon", "gallium-nitride"],
    processing_power: 2.33,
    cost_to_produce: 2.92,
    extra: 1,
    life_span_years: 1,
    release_date: "1995-02-04",
    volume_size_cm3: 8.42,
  },
  {
    model_name: "AFG-030",
    type: "sensor",
    material: ["silicon", "inp", "gaas"],
    processing_power: 2.2,
    cost_to_produce: 12.99,
    extra: 2,
    life_span_years: 15,
    release_date: "1999-02-06",
    volume_size_cm3: 1.87,
  },
  {
    model_name: "KPQ-795",
    type: "controller",
    material: ["inp", "indium-gallium-arsenide"],
    processing_power: 9.33,
    cost_to_produce: 29.16,
    extra: 2,
    life_span_years: 1,
    release_date: "2001-09-16",
    volume_size_cm3: 1.74,
  },
  {
    model_name: "FLK-568",
    type: "controller",
    material: ["sige"],
    processing_power: 9.59,
    cost_to_produce: 9.06,
    extra: 4,
    life_span_years: 9,
    release_date: "1999-09-20",
    volume_size_cm3: 0.1,
  },
  {
    model_name: "RFG-379",
    type: "gpu",
    material: ["gaas", "inp"],
    processing_power: 8.69,
    cost_to_produce: 8.74,
    extra: 2,
    life_span_years: 10,
    release_date: "2006-02-26",
    volume_size_cm3: 8.72,
  },
  {
    model_name: "AQK-576",
    type: "fpga",
    material: ["inp", "silicon-germanium"],
    processing_power: 6.93,
    cost_to_produce: 0.15,
    extra: 1,
    life_span_years: 14,
    release_date: "2025-09-08",
    volume_size_cm3: 1.3,
  },
  {
    model_name: "RVM-271",
    type: "sensor",
    material: ["silicon-germanium"],
    processing_power: 5.92,
    cost_to_produce: 25.77,
    extra: 2,
    life_span_years: 15,
    release_date: "1995-02-23",
    volume_size_cm3: 6.06,
  },
  {
    model_name: "FPC-209",
    type: "gpu",
    material: ["germanium", "indium-phosphide"],
    processing_power: 0.47,
    cost_to_produce: 23.33,
    extra: 5,
    life_span_years: 4,
    release_date: "2001-09-23",
    volume_size_cm3: 8.54,
  },
  {
    model_name: "ACW-228",
    type: "gpu",
    material: ["indium-gallium-arsenide"],
    processing_power: 5.89,
    cost_to_produce: 12.75,
    extra: 2,
    life_span_years: 5,
    release_date: "2007-03-13",
    volume_size_cm3: 7.18,
  },
  {
    model_name: "CIS-498",
    type: "ai-accelerator",
    material: ["gallium-nitride"],
    processing_power: 6.69,
    cost_to_produce: 24.88,
    extra: 1,
    life_span_years: 1,
    release_date: "2003-09-10",
    volume_size_cm3: 3.94,
  },
  {
    model_name: "OSC-943",
    type: "controller",
    material: ["inp"],
    processing_power: 7.15,
    cost_to_produce: 23.87,
    extra: 3,
    life_span_years: 7,
    release_date: "2013-05-30",
    volume_size_cm3: 1.04,
  },
  {
    model_name: "SBK-817",
    type: "controller",
    material: ["silicon-carbide", "gallium-arsenide", "silicon-germanium"],
    processing_power: 6.26,
    cost_to_produce: 25.77,
    extra: 4,
    life_span_years: 6,
    release_date: "2017-08-14",
    volume_size_cm3: 5.15,
  },
  {
    model_name: "YGZ-033",
    type: "fpga",
    material: ["germanium", "silicon"],
    processing_power: 4.61,
    cost_to_produce: 23.17,
    extra: 5,
    life_span_years: 2,
    release_date: "2014-04-14",
    volume_size_cm3: 3.33,
  },
  {
    model_name: "GGW-174",
    type: "fpga",
    material: ["gallium-nitride", "germanium", "indium-phosphide"],
    processing_power: 0.4,
    cost_to_produce: 12.1,
    extra: 3,
    life_span_years: 0,
    release_date: "2015-08-13",
    volume_size_cm3: 3.16,
  },
  {
    model_name: "CTT-890",
    type: "fpga",
    material: ["gan"],
    processing_power: 1.3,
    cost_to_produce: 22.7,
    extra: 1,
    life_span_years: 0,
    release_date: "2010-05-03",
    volume_size_cm3: 9.13,
  },
  {
    model_name: "QCE-021",
    type: "controller",
    material: ["sige"],
    processing_power: 1.13,
    cost_to_produce: 3.0,
    extra: 4,
    life_span_years: 1,
    release_date: "2014-10-18",
    volume_size_cm3: 5.62,
  },
  {
    model_name: "WOZ-544",
    type: "fpga",
    material: ["sige", "gan", "germanium"],
    processing_power: 8.38,
    cost_to_produce: 23.54,
    extra: 4,
    life_span_years: 5,
    release_date: "2011-05-16",
    volume_size_cm3: 7.79,
  },
  {
    model_name: "MQG-855",
    type: "controller",
    material: ["indium-gallium-arsenide", "silicon-carbide"],
    processing_power: 5.03,
    cost_to_produce: 5.39,
    extra: 3,
    life_span_years: 7,
    release_date: "2006-07-28",
    volume_size_cm3: 7.7,
  },
  {
    model_name: "VGC-231",
    type: "sensor",
    material: ["gallium-arsenide", "silicon-carbide"],
    processing_power: 1.58,
    cost_to_produce: 18.84,
    extra: 5,
    life_span_years: 0,
    release_date: "2003-02-07",
    volume_size_cm3: 3.62,
  },
  {
    model_name: "YIQ-725",
    type: "controller",
    material: ["indium-gallium-arsenide", "indium-phosphide", "gan"],
    processing_power: 10.0,
    cost_to_produce: 7.8,
    extra: 2,
    life_span_years: 11,
    release_date: "2021-09-11",
    volume_size_cm3: 1.44,
  },
  {
    model_name: "YBS-997",
    type: "sensor",
    material: ["gallium-arsenide", "silicon-carbide", "gallium-nitride"],
    processing_power: 5.16,
    cost_to_produce: 11.9,
    extra: 3,
    life_span_years: 0,
    release_date: "1997-07-30",
    volume_size_cm3: 9.74,
  },
  {
    model_name: "BCV-412",
    type: "ai-accelerator",
    material: ["gan", "gallium-arsenide"],
    processing_power: 4.09,
    cost_to_produce: 2.23,
    extra: 1,
    life_span_years: 9,
    release_date: "2001-06-27",
    volume_size_cm3: 3.59,
  },
  {
    model_name: "CWN-874",
    type: "sensor",
    material: ["indium-phosphide", "gan", "indium-gallium-arsenide"],
    processing_power: 0.43,
    cost_to_produce: 5.71,
    extra: 4,
    life_span_years: 13,
    release_date: "2019-05-14",
    volume_size_cm3: 5.41,
  },
  {
    model_name: "HEN-316",
    type: "gpu",
    material: ["sige", "germanium"],
    processing_power: 8.77,
    cost_to_produce: 29.91,
    extra: 5,
    life_span_years: 8,
    release_date: "2008-09-22",
    volume_size_cm3: 6.49,
  },
  {
    model_name: "OOU-131",
    type: "cpu",
    material: ["indium-gallium-arsenide"],
    processing_power: 0.18,
    cost_to_produce: 12.35,
    extra: 1,
    life_span_years: 6,
    release_date: "1996-02-20",
    volume_size_cm3: 7.88,
  },
  {
    model_name: "UPO-700",
    type: "ai-accelerator",
    material: ["indium-gallium-arsenide", "silicon-germanium"],
    processing_power: 0.95,
    cost_to_produce: 4.46,
    extra: 2,
    life_span_years: 9,
    release_date: "2004-08-21",
    volume_size_cm3: 4.97,
  },
  {
    model_name: "WUE-895",
    type: "ai-accelerator",
    material: ["germanium"],
    processing_power: 0.71,
    cost_to_produce: 3.41,
    extra: 3,
    life_span_years: 3,
    release_date: "2014-09-04",
    volume_size_cm3: 4.6,
  },
  {
    model_name: "LRD-593",
    type: "gpu",
    material: ["sige"],
    processing_power: 9.37,
    cost_to_produce: 4.6,
    extra: 1,
    life_span_years: 5,
    release_date: "1995-06-08",
    volume_size_cm3: 6.2,
  },
  {
    model_name: "EMH-411",
    type: "gpu",
    material: ["inp"],
    processing_power: 2.97,
    cost_to_produce: 25.27,
    extra: 5,
    life_span_years: 9,
    release_date: "2022-08-09",
    volume_size_cm3: 4.07,
  },
  {
    model_name: "YIC-224",
    type: "gpu",
    material: ["gan", "silicon-carbide", "gaas"],
    processing_power: 6.96,
    cost_to_produce: 9.49,
    extra: 1,
    life_span_years: 13,
    release_date: "2021-12-04",
    volume_size_cm3: 8.0,
  },
  {
    model_name: "ELM-113",
    type: "sensor",
    material: ["gallium-nitride"],
    processing_power: 0.66,
    cost_to_produce: 24.87,
    extra: 4,
    life_span_years: 2,
    release_date: "2013-02-12",
    volume_size_cm3: 6.42,
  },
  {
    model_name: "BWP-761",
    type: "gpu",
    material: ["germanium"],
    processing_power: 4.31,
    cost_to_produce: 29.55,
    extra: 3,
    life_span_years: 8,
    release_date: "2001-04-16",
    volume_size_cm3: 6.05,
  },
  {
    model_name: "QLD-336",
    type: "controller",
    material: ["gan", "sige"],
    processing_power: 8.94,
    cost_to_produce: 23.97,
    extra: 1,
    life_span_years: 14,
    release_date: "2014-08-09",
    volume_size_cm3: 4.7,
  },
  {
    model_name: "WIV-041",
    type: "ai-accelerator",
    material: ["gaas"],
    processing_power: 2.43,
    cost_to_produce: 9.43,
    extra: 1,
    life_span_years: 9,
    release_date: "2024-12-30",
    volume_size_cm3: 5.41,
  },
  {
    model_name: "WQF-108",
    type: "cpu",
    material: ["silicon-carbide", "indium-gallium-arsenide"],
    processing_power: 4.45,
    cost_to_produce: 5.06,
    extra: 2,
    life_span_years: 4,
    release_date: "2022-09-02",
    volume_size_cm3: 3.26,
  },
  {
    model_name: "XJH-933",
    type: "controller",
    material: ["silicon-carbide", "germanium", "sige"],
    processing_power: 8.13,
    cost_to_produce: 3.98,
    extra: 2,
    life_span_years: 6,
    release_date: "1997-12-22",
    volume_size_cm3: 9.09,
  },
  {
    model_name: "BME-445",
    type: "ai-accelerator",
    material: ["silicon-carbide", "gan"],
    processing_power: 4.32,
    cost_to_produce: 0.9,
    extra: 1,
    life_span_years: 10,
    release_date: "2008-10-13",
    volume_size_cm3: 8.73,
  },
  {
    model_name: "WQE-645",
    type: "cpu",
    material: ["germanium", "silicon-germanium", "inp"],
    processing_power: 5.17,
    cost_to_produce: 0.24,
    extra: 5,
    life_span_years: 14,
    release_date: "2025-01-25",
    volume_size_cm3: 4.1,
  },
  {
    model_name: "PGT-785",
    type: "cpu",
    material: ["gaas", "silicon-carbide"],
    processing_power: 5.37,
    cost_to_produce: 23.94,
    extra: 3,
    life_span_years: 12,
    release_date: "2025-02-14",
    volume_size_cm3: 2.48,
  },
  {
    model_name: "WZU-537",
    type: "gpu",
    material: ["silicon-germanium", "sige", "silicon"],
    processing_power: 2.86,
    cost_to_produce: 18.36,
    extra: 1,
    life_span_years: 11,
    release_date: "2019-02-09",
    volume_size_cm3: 0.91,
  },
  {
    model_name: "PZD-635",
    type: "ai-accelerator",
    material: ["germanium"],
    processing_power: 5.5,
    cost_to_produce: 3.47,
    extra: 1,
    life_span_years: 3,
    release_date: "2000-04-20",
    volume_size_cm3: 2.62,
  },
  {
    model_name: "BHP-031",
    type: "fpga",
    material: ["sige", "gan"],
    processing_power: 3.77,
    cost_to_produce: 10.79,
    extra: 5,
    life_span_years: 15,
    release_date: "2018-02-01",
    volume_size_cm3: 5.93,
  },
  {
    model_name: "RFO-173",
    type: "controller",
    material: ["gaas"],
    processing_power: 5.34,
    cost_to_produce: 16.3,
    extra: 2,
    life_span_years: 14,
    release_date: "1998-11-23",
    volume_size_cm3: 9.97,
  },
  {
    model_name: "SON-554",
    type: "sensor",
    material: ["silicon", "inp", "gan"],
    processing_power: 3.59,
    cost_to_produce: 16.37,
    extra: 1,
    life_span_years: 10,
    release_date: "2004-11-28",
    volume_size_cm3: 9.44,
  },
  {
    model_name: "JTN-190",
    type: "fpga",
    material: ["germanium", "indium-gallium-arsenide", "gaas"],
    processing_power: 6.26,
    cost_to_produce: 22.78,
    extra: 5,
    life_span_years: 15,
    release_date: "2007-08-08",
    volume_size_cm3: 3.3,
  },
  {
    model_name: "HAL-303",
    type: "gpu",
    material: ["germanium", "indium-gallium-arsenide"],
    processing_power: 2.03,
    cost_to_produce: 17.15,
    extra: 5,
    life_span_years: 2,
    release_date: "2003-10-12",
    volume_size_cm3: 3.01,
  },
  {
    model_name: "XPH-394",
    type: "gpu",
    material: ["germanium", "gan", "silicon-carbide"],
    processing_power: 5.78,
    cost_to_produce: 17.72,
    extra: 1,
    life_span_years: 4,
    release_date: "2012-06-04",
    volume_size_cm3: 0.98,
  },
  {
    model_name: "RNI-408",
    type: "cpu",
    material: ["indium-gallium-arsenide", "silicon", "gallium-arsenide"],
    processing_power: 7.85,
    cost_to_produce: 17.93,
    extra: 5,
    life_span_years: 2,
    release_date: "2022-12-11",
    volume_size_cm3: 7.31,
  },
  {
    model_name: "QOO-262",
    type: "ai-accelerator",
    material: ["gallium-nitride"],
    processing_power: 4.16,
    cost_to_produce: 7.93,
    extra: 1,
    life_span_years: 0,
    release_date: "2004-09-24",
    volume_size_cm3: 6.74,
  },
  {
    model_name: "EBC-958",
    type: "ai-accelerator",
    material: ["gallium-arsenide"],
    processing_power: 5.22,
    cost_to_produce: 27.08,
    extra: 4,
    life_span_years: 13,
    release_date: "2021-01-18",
    volume_size_cm3: 1.56,
  },
  {
    model_name: "TAW-527",
    type: "cpu",
    material: ["gan", "indium-phosphide"],
    processing_power: 3.84,
    cost_to_produce: 17.71,
    extra: 1,
    life_span_years: 8,
    release_date: "2015-05-24",
    volume_size_cm3: 3.89,
  },
  {
    model_name: "HCC-457",
    type: "gpu",
    material: ["indium-phosphide"],
    processing_power: 5.49,
    cost_to_produce: 8.12,
    extra: 5,
    life_span_years: 7,
    release_date: "2024-06-10",
    volume_size_cm3: 6.21,
  },
  {
    model_name: "CJG-396",
    type: "cpu",
    material: ["germanium"],
    processing_power: 8.78,
    cost_to_produce: 4.56,
    extra: 3,
    life_span_years: 2,
    release_date: "2025-06-17",
    volume_size_cm3: 6.8,
  },
  {
    model_name: "JEK-705",
    type: "gpu",
    material: ["gaas", "germanium"],
    processing_power: 8.77,
    cost_to_produce: 25.36,
    extra: 2,
    life_span_years: 10,
    release_date: "2025-11-17",
    volume_size_cm3: 0.85,
  },
  {
    model_name: "SKN-420",
    type: "gpu",
    material: ["indium-gallium-arsenide"],
    processing_power: 9.23,
    cost_to_produce: 21.14,
    extra: 1,
    life_span_years: 8,
    release_date: "1997-03-15",
    volume_size_cm3: 2.97,
  },
  {
    model_name: "BCZ-882",
    type: "fpga",
    material: ["sige"],
    processing_power: 9.49,
    cost_to_produce: 28.42,
    extra: 2,
    life_span_years: 4,
    release_date: "2024-12-17",
    volume_size_cm3: 9.21,
  },
  {
    model_name: "DBP-542",
    type: "fpga",
    material: ["gallium-nitride"],
    processing_power: 4.06,
    cost_to_produce: 12.55,
    extra: 4,
    life_span_years: 13,
    release_date: "2016-11-28",
    volume_size_cm3: 3.45,
  },
  {
    model_name: "SDV-128",
    type: "ai-accelerator",
    material: ["inp", "silicon", "silicon-germanium"],
    processing_power: 1.67,
    cost_to_produce: 0.2,
    extra: 5,
    life_span_years: 14,
    release_date: "2020-10-07",
    volume_size_cm3: 9.12,
  },
  {
    model_name: "KTC-017",
    type: "fpga",
    material: ["silicon", "inp"],
    processing_power: 5.62,
    cost_to_produce: 7.9,
    extra: 4,
    life_span_years: 11,
    release_date: "2015-07-11",
    volume_size_cm3: 2.89,
  },
  {
    model_name: "JOS-973",
    type: "controller",
    material: [
      "indium-phosphide",
      "indium-gallium-arsenide",
      "silicon-carbide",
    ],
    processing_power: 0.1,
    cost_to_produce: 21.52,
    extra: 5,
    life_span_years: 10,
    release_date: "1999-08-12",
    volume_size_cm3: 7.86,
  },
  {
    model_name: "JOF-158",
    type: "gpu",
    material: ["indium-gallium-arsenide", "indium-phosphide", "germanium"],
    processing_power: 9.05,
    cost_to_produce: 26.05,
    extra: 5,
    life_span_years: 9,
    release_date: "1998-11-22",
    volume_size_cm3: 5.18,
  },
  {
    model_name: "RWY-855",
    type: "gpu",
    material: ["silicon-germanium", "gallium-nitride"],
    processing_power: 2.67,
    cost_to_produce: 16.48,
    extra: 5,
    life_span_years: 11,
    release_date: "1995-01-20",
    volume_size_cm3: 5.33,
  },
  {
    model_name: "SGB-303",
    type: "sensor",
    material: ["gallium-arsenide", "gaas"],
    processing_power: 5.11,
    cost_to_produce: 21.23,
    extra: 3,
    life_span_years: 6,
    release_date: "2018-10-27",
    volume_size_cm3: 8.93,
  },
];
