import { Semiconductor } from "@/types";

export const mock_50: Semiconductor[] = [
  {
    model_name: "KRX-139",
    type: "cpu",
    material: ["sige", "indium-phosphide", "gallium-nitride"],
    processing_power: 2.96,
    cost_to_produce: 21.76,
    extra: 1,
    life_span_years: 9,
    release_date: "2020-07-05",
    volume_size_cm3: 4.51,
  },
  {
    model_name: "RTD-918",
    type: "fpga",
    material: ["indium-gallium-arsenide", "inp", "germanium"],
    processing_power: 3.42,
    cost_to_produce: 26.83,
    extra: 3,
    life_span_years: 2,
    release_date: "1998-11-01",
    volume_size_cm3: 6.33,
  },
  {
    model_name: "YSB-971",
    type: "gpu",
    material: ["gallium-nitride"],
    processing_power: 0.31,
    cost_to_produce: 16.25,
    extra: 2,
    life_span_years: 9,
    release_date: "2002-11-27",
    volume_size_cm3: 9.7,
  },
  {
    model_name: "NXJ-144",
    type: "controller",
    material: ["gan", "indium-phosphide"],
    processing_power: 7.64,
    cost_to_produce: 17.21,
    extra: 3,
    life_span_years: 7,
    release_date: "2023-10-22",
    volume_size_cm3: 5.29,
  },
  {
    model_name: "KMO-169",
    type: "controller",
    material: ["indium-phosphide", "silicon-carbide"],
    processing_power: 7.41,
    cost_to_produce: 9.51,
    extra: 2,
    life_span_years: 15,
    release_date: "2021-03-24",
    volume_size_cm3: 6.58,
  },
  {
    model_name: "UEY-439",
    type: "sensor",
    material: ["indium-phosphide", "silicon-carbide", "gallium-nitride"],
    processing_power: 5.24,
    cost_to_produce: 29.95,
    extra: 4,
    life_span_years: 8,
    release_date: "2023-10-24",
    volume_size_cm3: 2.69,
  },
  {
    model_name: "QEV-286",
    type: "gpu",
    material: ["silicon-germanium", "inp"],
    processing_power: 4.15,
    cost_to_produce: 5.37,
    extra: 2,
    life_span_years: 2,
    release_date: "2024-03-04",
    volume_size_cm3: 3.03,
  },
  {
    model_name: "ZSA-303",
    type: "gpu",
    material: ["silicon-carbide", "gaas"],
    processing_power: 4.15,
    cost_to_produce: 23.47,
    extra: 1,
    life_span_years: 6,
    release_date: "1996-07-16",
    volume_size_cm3: 4.78,
  },
  {
    model_name: "YCY-114",
    type: "sensor",
    material: ["gallium-nitride"],
    processing_power: 1.11,
    cost_to_produce: 16.2,
    extra: 2,
    life_span_years: 4,
    release_date: "2004-12-31",
    volume_size_cm3: 9.76,
  },
  {
    model_name: "WRQ-270",
    type: "controller",
    material: ["indium-gallium-arsenide", "gan"],
    processing_power: 2.94,
    cost_to_produce: 23.97,
    extra: 3,
    life_span_years: 9,
    release_date: "2010-04-09",
    volume_size_cm3: 1.8,
  },
  {
    model_name: "YPQ-793",
    type: "controller",
    material: ["silicon", "inp"],
    processing_power: 7.52,
    cost_to_produce: 29.53,
    extra: 1,
    life_span_years: 14,
    release_date: "1998-01-03",
    volume_size_cm3: 5.06,
  },
  {
    model_name: "BZP-099",
    type: "gpu",
    material: ["indium-gallium-arsenide", "sige", "silicon-carbide"],
    processing_power: 4.53,
    cost_to_produce: 10.03,
    extra: 5,
    life_span_years: 7,
    release_date: "1996-10-08",
    volume_size_cm3: 3.03,
  },
  {
    model_name: "LMZ-389",
    type: "sensor",
    material: ["silicon-germanium", "silicon-carbide", "silicon"],
    processing_power: 9.66,
    cost_to_produce: 27.06,
    extra: 3,
    life_span_years: 3,
    release_date: "2016-10-05",
    volume_size_cm3: 5.45,
  },
  {
    model_name: "XHT-318",
    type: "controller",
    material: [
      "silicon-carbide",
      "indium-gallium-arsenide",
      "gallium-arsenide",
    ],
    processing_power: 0.33,
    cost_to_produce: 23.27,
    extra: 4,
    life_span_years: 3,
    release_date: "2004-06-02",
    volume_size_cm3: 0.92,
  },
  {
    model_name: "FFQ-314",
    type: "cpu",
    material: ["sige", "germanium", "silicon"],
    processing_power: 5.08,
    cost_to_produce: 10.29,
    extra: 4,
    life_span_years: 11,
    release_date: "2010-05-30",
    volume_size_cm3: 2.45,
  },
  {
    model_name: "HRK-834",
    type: "fpga",
    material: ["silicon-carbide", "indium-gallium-arsenide"],
    processing_power: 9.14,
    cost_to_produce: 27.93,
    extra: 3,
    life_span_years: 3,
    release_date: "1995-03-13",
    volume_size_cm3: 7.38,
  },
  {
    model_name: "EXM-431",
    type: "sensor",
    material: ["gallium-nitride"],
    processing_power: 7.85,
    cost_to_produce: 23.83,
    extra: 1,
    life_span_years: 12,
    release_date: "2022-12-13",
    volume_size_cm3: 2.25,
  },
  {
    model_name: "UZF-173",
    type: "controller",
    material: ["gallium-nitride", "gaas", "sige"],
    processing_power: 8.25,
    cost_to_produce: 0.64,
    extra: 3,
    life_span_years: 3,
    release_date: "2014-08-18",
    volume_size_cm3: 9.51,
  },
  {
    model_name: "VOD-608",
    type: "ai-accelerator",
    material: ["indium-phosphide", "indium-gallium-arsenide"],
    processing_power: 2.01,
    cost_to_produce: 13.77,
    extra: 4,
    life_span_years: 5,
    release_date: "2011-04-10",
    volume_size_cm3: 9.1,
  },
  {
    model_name: "NMD-488",
    type: "cpu",
    material: ["gaas", "silicon-carbide", "silicon-germanium"],
    processing_power: 9.51,
    cost_to_produce: 24.6,
    extra: 4,
    life_span_years: 0,
    release_date: "2016-10-23",
    volume_size_cm3: 7.88,
  },
  {
    model_name: "OTB-845",
    type: "fpga",
    material: ["inp", "germanium"],
    processing_power: 8.38,
    cost_to_produce: 17.77,
    extra: 1,
    life_span_years: 0,
    release_date: "2005-10-19",
    volume_size_cm3: 8.99,
  },
  {
    model_name: "JKF-884",
    type: "controller",
    material: ["silicon-germanium", "indium-gallium-arsenide", "gaas"],
    processing_power: 4.16,
    cost_to_produce: 23.14,
    extra: 1,
    life_span_years: 1,
    release_date: "2013-01-05",
    volume_size_cm3: 3.45,
  },
  {
    model_name: "OYF-861",
    type: "controller",
    material: [
      "silicon-carbide",
      "indium-gallium-arsenide",
      "silicon-germanium",
    ],
    processing_power: 7.14,
    cost_to_produce: 26.51,
    extra: 3,
    life_span_years: 6,
    release_date: "2018-07-22",
    volume_size_cm3: 6.57,
  },
  {
    model_name: "FTD-531",
    type: "fpga",
    material: ["gallium-arsenide", "indium-gallium-arsenide", "sige"],
    processing_power: 5.04,
    cost_to_produce: 24.66,
    extra: 3,
    life_span_years: 1,
    release_date: "2025-08-09",
    volume_size_cm3: 6.02,
  },
  {
    model_name: "SJK-920",
    type: "controller",
    material: ["silicon"],
    processing_power: 7.88,
    cost_to_produce: 17.91,
    extra: 1,
    life_span_years: 7,
    release_date: "2001-06-03",
    volume_size_cm3: 2.23,
  },
  {
    model_name: "VTK-480",
    type: "cpu",
    material: ["sige", "gallium-arsenide"],
    processing_power: 4.67,
    cost_to_produce: 2.27,
    extra: 4,
    life_span_years: 10,
    release_date: "2012-03-30",
    volume_size_cm3: 7.07,
  },
  {
    model_name: "XDZ-572",
    type: "sensor",
    material: ["inp"],
    processing_power: 7.39,
    cost_to_produce: 29.21,
    extra: 1,
    life_span_years: 5,
    release_date: "2004-08-16",
    volume_size_cm3: 4.58,
  },
  {
    model_name: "IUQ-999",
    type: "ai-accelerator",
    material: ["silicon-carbide", "gallium-arsenide", "sige"],
    processing_power: 7.44,
    cost_to_produce: 15.28,
    extra: 3,
    life_span_years: 7,
    release_date: "2012-05-07",
    volume_size_cm3: 2.14,
  },
  {
    model_name: "TTV-267",
    type: "fpga",
    material: ["silicon-germanium"],
    processing_power: 5.91,
    cost_to_produce: 5.08,
    extra: 3,
    life_span_years: 14,
    release_date: "2014-01-24",
    volume_size_cm3: 9.4,
  },
  {
    model_name: "MYK-582",
    type: "sensor",
    material: ["silicon-germanium"],
    processing_power: 6.61,
    cost_to_produce: 15.5,
    extra: 4,
    life_span_years: 10,
    release_date: "2025-07-27",
    volume_size_cm3: 1.53,
  },
  {
    model_name: "OGU-725",
    type: "gpu",
    material: ["gan", "germanium"],
    processing_power: 4.24,
    cost_to_produce: 13.41,
    extra: 4,
    life_span_years: 1,
    release_date: "2010-10-12",
    volume_size_cm3: 3.18,
  },
  {
    model_name: "BEC-334",
    type: "gpu",
    material: ["silicon-carbide", "gaas"],
    processing_power: 7.17,
    cost_to_produce: 17.56,
    extra: 3,
    life_span_years: 14,
    release_date: "2025-12-19",
    volume_size_cm3: 4.35,
  },
  {
    model_name: "ICG-790",
    type: "ai-accelerator",
    material: ["gaas"],
    processing_power: 1.68,
    cost_to_produce: 24.02,
    extra: 3,
    life_span_years: 2,
    release_date: "1999-09-30",
    volume_size_cm3: 1.81,
  },
  {
    model_name: "HHB-783",
    type: "fpga",
    material: ["sige", "silicon-carbide"],
    processing_power: 2.71,
    cost_to_produce: 28.25,
    extra: 1,
    life_span_years: 15,
    release_date: "1999-08-14",
    volume_size_cm3: 8.91,
  },
  {
    model_name: "KSV-303",
    type: "fpga",
    material: ["silicon", "indium-gallium-arsenide"],
    processing_power: 1.04,
    cost_to_produce: 1.2,
    extra: 5,
    life_span_years: 3,
    release_date: "2021-04-12",
    volume_size_cm3: 4.63,
  },
  {
    model_name: "FAI-329",
    type: "ai-accelerator",
    material: ["inp"],
    processing_power: 8.88,
    cost_to_produce: 26.35,
    extra: 3,
    life_span_years: 8,
    release_date: "2011-08-23",
    volume_size_cm3: 9.96,
  },
  {
    model_name: "ELX-665",
    type: "ai-accelerator",
    material: ["silicon-carbide", "gallium-arsenide"],
    processing_power: 8.85,
    cost_to_produce: 9.5,
    extra: 3,
    life_span_years: 0,
    release_date: "2019-05-01",
    volume_size_cm3: 3.02,
  },
  {
    model_name: "ZJR-140",
    type: "cpu",
    material: ["inp"],
    processing_power: 8.97,
    cost_to_produce: 20.12,
    extra: 2,
    life_span_years: 7,
    release_date: "2010-12-12",
    volume_size_cm3: 7.98,
  },
  {
    model_name: "ILH-376",
    type: "cpu",
    material: ["gaas", "silicon", "silicon-carbide"],
    processing_power: 9.2,
    cost_to_produce: 8.4,
    extra: 4,
    life_span_years: 5,
    release_date: "2003-05-30",
    volume_size_cm3: 7.19,
  },
  {
    model_name: "TJC-195",
    type: "fpga",
    material: ["silicon-germanium", "silicon-carbide"],
    processing_power: 2.36,
    cost_to_produce: 25.03,
    extra: 2,
    life_span_years: 11,
    release_date: "2003-05-25",
    volume_size_cm3: 7.33,
  },
  {
    model_name: "SVQ-180",
    type: "ai-accelerator",
    material: ["silicon", "silicon-germanium"],
    processing_power: 0.93,
    cost_to_produce: 19.06,
    extra: 5,
    life_span_years: 13,
    release_date: "2021-10-15",
    volume_size_cm3: 7.88,
  },
  {
    model_name: "ZGU-485",
    type: "cpu",
    material: ["gan", "silicon-carbide", "germanium"],
    processing_power: 4.57,
    cost_to_produce: 28.7,
    extra: 1,
    life_span_years: 14,
    release_date: "2014-06-02",
    volume_size_cm3: 2.86,
  },
  {
    model_name: "JXH-121",
    type: "gpu",
    material: ["germanium"],
    processing_power: 0.45,
    cost_to_produce: 6.2,
    extra: 2,
    life_span_years: 15,
    release_date: "2008-03-09",
    volume_size_cm3: 6.79,
  },
  {
    model_name: "WFS-410",
    type: "fpga",
    material: ["silicon", "silicon-carbide", "gaas"],
    processing_power: 7.75,
    cost_to_produce: 20.4,
    extra: 3,
    life_span_years: 14,
    release_date: "1996-12-07",
    volume_size_cm3: 9.28,
  },
  {
    model_name: "RVB-936",
    type: "gpu",
    material: ["inp", "gallium-arsenide", "silicon"],
    processing_power: 5.96,
    cost_to_produce: 20.93,
    extra: 1,
    life_span_years: 3,
    release_date: "2015-09-03",
    volume_size_cm3: 5.46,
  },
  {
    model_name: "MGS-009",
    type: "sensor",
    material: ["indium-phosphide"],
    processing_power: 7.29,
    cost_to_produce: 19.81,
    extra: 1,
    life_span_years: 11,
    release_date: "2008-05-11",
    volume_size_cm3: 9.7,
  },
  {
    model_name: "VRR-461",
    type: "cpu",
    material: ["inp", "silicon-carbide", "gaas"],
    processing_power: 0.11,
    cost_to_produce: 26.73,
    extra: 5,
    life_span_years: 8,
    release_date: "2010-12-25",
    volume_size_cm3: 7.84,
  },
  {
    model_name: "STA-653",
    type: "controller",
    material: ["sige", "gaas"],
    processing_power: 4.66,
    cost_to_produce: 22.99,
    extra: 3,
    life_span_years: 12,
    release_date: "2018-01-01",
    volume_size_cm3: 4.17,
  },
  {
    model_name: "IYB-833",
    type: "cpu",
    material: ["gallium-nitride", "indium-gallium-arsenide", "inp"],
    processing_power: 0.71,
    cost_to_produce: 9.96,
    extra: 4,
    life_span_years: 15,
    release_date: "2013-06-25",
    volume_size_cm3: 1.05,
  },
  {
    model_name: "DGL-459",
    type: "controller",
    material: ["sige", "silicon"],
    processing_power: 6.64,
    cost_to_produce: 9.82,
    extra: 5,
    life_span_years: 3,
    release_date: "2007-06-13",
    volume_size_cm3: 9.9,
  },
];
