import { Semiconductor } from "@/types";

export const mock_200: Semiconductor[] = [
  {
    model_name: "MXF-960",
    type: "controller",
    material: ["germanium", "inp"],
    processing_power: 0.61,
    cost_to_produce: 17.29,
    extra: 2,
    life_span_years: 7,
    release_date: "1998-11-11",
    volume_size_cm3: 5.31,
  },
  {
    model_name: "DTM-179",
    type: "gpu",
    material: ["indium-phosphide", "silicon-carbide", "silicon-germanium"],
    processing_power: 7.6,
    cost_to_produce: 19.36,
    extra: 4,
    life_span_years: 11,
    release_date: "2002-03-26",
    volume_size_cm3: 4.46,
  },
  {
    model_name: "PLH-411",
    type: "gpu",
    material: ["sige", "gan", "inp"],
    processing_power: 5.67,
    cost_to_produce: 6.02,
    extra: 2,
    life_span_years: 11,
    release_date: "2009-04-19",
    volume_size_cm3: 9.48,
  },
  {
    model_name: "BFF-783",
    type: "controller",
    material: [
      "indium-phosphide",
      "indium-gallium-arsenide",
      "silicon-carbide",
    ],
    processing_power: 6.34,
    cost_to_produce: 3.12,
    extra: 4,
    life_span_years: 3,
    release_date: "1995-06-21",
    volume_size_cm3: 0.64,
  },
  {
    model_name: "AVC-537",
    type: "controller",
    material: ["silicon", "gaas"],
    processing_power: 9.16,
    cost_to_produce: 17.94,
    extra: 1,
    life_span_years: 2,
    release_date: "2020-07-15",
    volume_size_cm3: 6.88,
  },
  {
    model_name: "PUN-574",
    type: "gpu",
    material: ["gallium-nitride", "inp", "gan"],
    processing_power: 7.82,
    cost_to_produce: 14.0,
    extra: 1,
    life_span_years: 12,
    release_date: "2021-09-12",
    volume_size_cm3: 9.78,
  },
  {
    model_name: "HQK-611",
    type: "ai-accelerator",
    material: ["germanium", "silicon-carbide", "gallium-arsenide"],
    processing_power: 4.2,
    cost_to_produce: 21.53,
    extra: 5,
    life_span_years: 15,
    release_date: "2000-08-05",
    volume_size_cm3: 4.12,
  },
  {
    model_name: "HFP-875",
    type: "gpu",
    material: ["silicon-carbide"],
    processing_power: 5.53,
    cost_to_produce: 13.42,
    extra: 3,
    life_span_years: 14,
    release_date: "2007-09-18",
    volume_size_cm3: 5.22,
  },
  {
    model_name: "QYB-705",
    type: "ai-accelerator",
    material: ["inp", "indium-gallium-arsenide"],
    processing_power: 4.03,
    cost_to_produce: 5.68,
    extra: 1,
    life_span_years: 7,
    release_date: "2012-09-14",
    volume_size_cm3: 5.02,
  },
  {
    model_name: "ZRS-774",
    type: "gpu",
    material: ["gallium-nitride", "silicon", "indium-gallium-arsenide"],
    processing_power: 6.18,
    cost_to_produce: 3.97,
    extra: 4,
    life_span_years: 4,
    release_date: "2010-06-02",
    volume_size_cm3: 2.9,
  },
  {
    model_name: "GFU-353",
    type: "controller",
    material: ["silicon-carbide", "sige", "indium-phosphide"],
    processing_power: 1.63,
    cost_to_produce: 4.23,
    extra: 5,
    life_span_years: 15,
    release_date: "2015-06-08",
    volume_size_cm3: 4.08,
  },
  {
    model_name: "VFY-631",
    type: "fpga",
    material: ["germanium"],
    processing_power: 1.7,
    cost_to_produce: 0.43,
    extra: 3,
    life_span_years: 2,
    release_date: "2013-01-21",
    volume_size_cm3: 5.81,
  },
  {
    model_name: "HIY-879",
    type: "ai-accelerator",
    material: ["indium-gallium-arsenide"],
    processing_power: 8.57,
    cost_to_produce: 7.59,
    extra: 5,
    life_span_years: 6,
    release_date: "2014-05-21",
    volume_size_cm3: 0.74,
  },
  {
    model_name: "VTU-565",
    type: "ai-accelerator",
    material: ["sige"],
    processing_power: 3.02,
    cost_to_produce: 5.4,
    extra: 1,
    life_span_years: 6,
    release_date: "1996-05-05",
    volume_size_cm3: 4.22,
  },
  {
    model_name: "JFN-577",
    type: "fpga",
    material: ["inp", "gaas"],
    processing_power: 5.72,
    cost_to_produce: 24.16,
    extra: 5,
    life_span_years: 5,
    release_date: "2021-02-28",
    volume_size_cm3: 9.43,
  },
  {
    model_name: "MKL-661",
    type: "fpga",
    material: ["indium-gallium-arsenide", "gan", "inp"],
    processing_power: 3.93,
    cost_to_produce: 20.89,
    extra: 3,
    life_span_years: 7,
    release_date: "2008-02-29",
    volume_size_cm3: 9.37,
  },
  {
    model_name: "WYI-440",
    type: "ai-accelerator",
    material: ["sige", "silicon", "germanium"],
    processing_power: 8.14,
    cost_to_produce: 6.5,
    extra: 2,
    life_span_years: 7,
    release_date: "2011-01-23",
    volume_size_cm3: 7.56,
  },
  {
    model_name: "SIB-282",
    type: "gpu",
    material: ["silicon-germanium"],
    processing_power: 9.17,
    cost_to_produce: 9.92,
    extra: 2,
    life_span_years: 2,
    release_date: "2006-07-01",
    volume_size_cm3: 5.11,
  },
  {
    model_name: "UHP-975",
    type: "ai-accelerator",
    material: ["indium-phosphide", "silicon-germanium", "gaas"],
    processing_power: 7.52,
    cost_to_produce: 7.84,
    extra: 1,
    life_span_years: 3,
    release_date: "1997-07-30",
    volume_size_cm3: 4.31,
  },
  {
    model_name: "FPY-739",
    type: "sensor",
    material: ["gallium-nitride"],
    processing_power: 5.97,
    cost_to_produce: 19.5,
    extra: 4,
    life_span_years: 14,
    release_date: "2022-12-29",
    volume_size_cm3: 2.72,
  },
  {
    model_name: "UBG-505",
    type: "cpu",
    material: ["gallium-arsenide", "sige", "germanium"],
    processing_power: 0.58,
    cost_to_produce: 8.63,
    extra: 5,
    life_span_years: 1,
    release_date: "2005-10-18",
    volume_size_cm3: 5.19,
  },
  {
    model_name: "FTM-111",
    type: "gpu",
    material: ["gan", "gallium-arsenide", "sige"],
    processing_power: 4.9,
    cost_to_produce: 17.54,
    extra: 3,
    life_span_years: 5,
    release_date: "1995-06-30",
    volume_size_cm3: 2.81,
  },
  {
    model_name: "OWN-638",
    type: "sensor",
    material: ["gaas", "indium-phosphide", "gan"],
    processing_power: 9.23,
    cost_to_produce: 10.89,
    extra: 4,
    life_span_years: 9,
    release_date: "2007-05-13",
    volume_size_cm3: 6.49,
  },
  {
    model_name: "OHI-937",
    type: "ai-accelerator",
    material: [
      "indium-gallium-arsenide",
      "silicon-carbide",
      "silicon-germanium",
    ],
    processing_power: 8.06,
    cost_to_produce: 7.88,
    extra: 1,
    life_span_years: 8,
    release_date: "1999-05-13",
    volume_size_cm3: 4.89,
  },
  {
    model_name: "JOK-392",
    type: "ai-accelerator",
    material: ["sige", "gallium-nitride"],
    processing_power: 7.59,
    cost_to_produce: 17.85,
    extra: 4,
    life_span_years: 7,
    release_date: "1997-11-15",
    volume_size_cm3: 8.3,
  },
  {
    model_name: "BIY-905",
    type: "gpu",
    material: ["silicon-germanium", "germanium"],
    processing_power: 2.49,
    cost_to_produce: 9.26,
    extra: 2,
    life_span_years: 6,
    release_date: "2017-08-29",
    volume_size_cm3: 4.78,
  },
  {
    model_name: "CXX-829",
    type: "cpu",
    material: ["sige", "inp", "gallium-arsenide"],
    processing_power: 6.96,
    cost_to_produce: 28.64,
    extra: 2,
    life_span_years: 1,
    release_date: "2021-04-05",
    volume_size_cm3: 7.01,
  },
  {
    model_name: "ETV-638",
    type: "cpu",
    material: ["gaas"],
    processing_power: 3.88,
    cost_to_produce: 12.13,
    extra: 1,
    life_span_years: 7,
    release_date: "2007-03-28",
    volume_size_cm3: 1.58,
  },
  {
    model_name: "LHK-653",
    type: "fpga",
    material: ["gan"],
    processing_power: 1.87,
    cost_to_produce: 29.08,
    extra: 4,
    life_span_years: 4,
    release_date: "2014-09-05",
    volume_size_cm3: 3.11,
  },
  {
    model_name: "NXK-404",
    type: "cpu",
    material: ["sige", "gallium-nitride", "silicon"],
    processing_power: 8.66,
    cost_to_produce: 26.34,
    extra: 1,
    life_span_years: 12,
    release_date: "2003-04-01",
    volume_size_cm3: 7.58,
  },
  {
    model_name: "XSP-925",
    type: "sensor",
    material: ["silicon-carbide", "gallium-arsenide", "silicon"],
    processing_power: 5.25,
    cost_to_produce: 1.8,
    extra: 3,
    life_span_years: 14,
    release_date: "1995-11-01",
    volume_size_cm3: 6.28,
  },
  {
    model_name: "JIV-180",
    type: "sensor",
    material: ["silicon"],
    processing_power: 4.24,
    cost_to_produce: 26.94,
    extra: 4,
    life_span_years: 14,
    release_date: "2009-11-16",
    volume_size_cm3: 1.17,
  },
  {
    model_name: "IWC-390",
    type: "sensor",
    material: ["gallium-arsenide"],
    processing_power: 9.62,
    cost_to_produce: 1.44,
    extra: 1,
    life_span_years: 14,
    release_date: "2000-11-08",
    volume_size_cm3: 5.3,
  },
  {
    model_name: "RCX-007",
    type: "cpu",
    material: ["sige"],
    processing_power: 2.06,
    cost_to_produce: 27.34,
    extra: 3,
    life_span_years: 3,
    release_date: "2022-06-26",
    volume_size_cm3: 5.17,
  },
  {
    model_name: "RMG-333",
    type: "cpu",
    material: ["germanium", "sige"],
    processing_power: 5.75,
    cost_to_produce: 20.66,
    extra: 2,
    life_span_years: 3,
    release_date: "2011-07-16",
    volume_size_cm3: 9.87,
  },
  {
    model_name: "WKW-894",
    type: "gpu",
    material: ["sige", "inp"],
    processing_power: 4.68,
    cost_to_produce: 16.04,
    extra: 5,
    life_span_years: 14,
    release_date: "2003-12-20",
    volume_size_cm3: 0.61,
  },
  {
    model_name: "GOK-989",
    type: "sensor",
    material: ["sige", "inp", "silicon-carbide"],
    processing_power: 4.19,
    cost_to_produce: 8.91,
    extra: 1,
    life_span_years: 7,
    release_date: "1997-05-07",
    volume_size_cm3: 4.43,
  },
  {
    model_name: "HXZ-841",
    type: "sensor",
    material: ["germanium"],
    processing_power: 9.35,
    cost_to_produce: 3.94,
    extra: 1,
    life_span_years: 6,
    release_date: "2016-04-27",
    volume_size_cm3: 9.66,
  },
  {
    model_name: "ALO-400",
    type: "controller",
    material: ["inp", "gallium-nitride"],
    processing_power: 0.51,
    cost_to_produce: 18.5,
    extra: 2,
    life_span_years: 5,
    release_date: "2021-02-15",
    volume_size_cm3: 1.08,
  },
  {
    model_name: "WVN-527",
    type: "sensor",
    material: ["germanium", "indium-phosphide"],
    processing_power: 2.28,
    cost_to_produce: 6.3,
    extra: 2,
    life_span_years: 15,
    release_date: "1996-06-13",
    volume_size_cm3: 0.66,
  },
  {
    model_name: "XFU-749",
    type: "sensor",
    material: ["gan", "silicon-germanium", "germanium"],
    processing_power: 9.48,
    cost_to_produce: 0.22,
    extra: 1,
    life_span_years: 13,
    release_date: "2007-04-18",
    volume_size_cm3: 8.84,
  },
  {
    model_name: "JMX-819",
    type: "ai-accelerator",
    material: ["indium-phosphide", "gan"],
    processing_power: 7.21,
    cost_to_produce: 7.44,
    extra: 4,
    life_span_years: 11,
    release_date: "2011-09-06",
    volume_size_cm3: 4.04,
  },
  {
    model_name: "ZRL-105",
    type: "fpga",
    material: ["indium-phosphide"],
    processing_power: 8.45,
    cost_to_produce: 23.98,
    extra: 1,
    life_span_years: 12,
    release_date: "2010-03-21",
    volume_size_cm3: 8.71,
  },
  {
    model_name: "KMM-954",
    type: "controller",
    material: ["germanium"],
    processing_power: 8.98,
    cost_to_produce: 20.03,
    extra: 1,
    life_span_years: 9,
    release_date: "1996-10-31",
    volume_size_cm3: 6.84,
  },
  {
    model_name: "OBE-865",
    type: "controller",
    material: ["gallium-arsenide", "germanium"],
    processing_power: 3.63,
    cost_to_produce: 26.63,
    extra: 2,
    life_span_years: 0,
    release_date: "2000-01-26",
    volume_size_cm3: 9.1,
  },
  {
    model_name: "PLU-186",
    type: "ai-accelerator",
    material: ["indium-phosphide", "sige", "gallium-arsenide"],
    processing_power: 7.66,
    cost_to_produce: 0.36,
    extra: 4,
    life_span_years: 3,
    release_date: "2010-09-25",
    volume_size_cm3: 6.88,
  },
  {
    model_name: "TDH-680",
    type: "fpga",
    material: ["gallium-arsenide"],
    processing_power: 8.96,
    cost_to_produce: 12.14,
    extra: 5,
    life_span_years: 4,
    release_date: "2020-11-11",
    volume_size_cm3: 8.19,
  },
  {
    model_name: "SEL-311",
    type: "cpu",
    material: ["gallium-arsenide"],
    processing_power: 0.82,
    cost_to_produce: 26.25,
    extra: 4,
    life_span_years: 15,
    release_date: "2002-02-15",
    volume_size_cm3: 2.44,
  },
  {
    model_name: "RRO-612",
    type: "fpga",
    material: ["indium-phosphide", "gan", "germanium"],
    processing_power: 8.98,
    cost_to_produce: 8.49,
    extra: 4,
    life_span_years: 1,
    release_date: "2023-06-12",
    volume_size_cm3: 6.65,
  },
  {
    model_name: "OQR-178",
    type: "ai-accelerator",
    material: ["germanium", "silicon"],
    processing_power: 7.8,
    cost_to_produce: 20.66,
    extra: 1,
    life_span_years: 7,
    release_date: "2021-06-14",
    volume_size_cm3: 2.01,
  },
  {
    model_name: "GVS-879",
    type: "controller",
    material: ["gallium-arsenide", "silicon"],
    processing_power: 2.65,
    cost_to_produce: 28.35,
    extra: 1,
    life_span_years: 4,
    release_date: "2025-02-20",
    volume_size_cm3: 7.02,
  },
  {
    model_name: "RUJ-709",
    type: "ai-accelerator",
    material: ["indium-gallium-arsenide", "gallium-nitride", "inp"],
    processing_power: 1.33,
    cost_to_produce: 9.29,
    extra: 3,
    life_span_years: 11,
    release_date: "2015-08-18",
    volume_size_cm3: 3.19,
  },
  {
    model_name: "ZCF-255",
    type: "fpga",
    material: ["gan"],
    processing_power: 7.22,
    cost_to_produce: 13.48,
    extra: 2,
    life_span_years: 3,
    release_date: "2009-07-25",
    volume_size_cm3: 4.39,
  },
  {
    model_name: "QOX-112",
    type: "sensor",
    material: ["sige", "gaas", "silicon-germanium"],
    processing_power: 3.93,
    cost_to_produce: 28.16,
    extra: 5,
    life_span_years: 7,
    release_date: "2017-01-22",
    volume_size_cm3: 3.34,
  },
  {
    model_name: "BCP-963",
    type: "cpu",
    material: ["indium-gallium-arsenide", "inp", "gallium-nitride"],
    processing_power: 0.83,
    cost_to_produce: 6.08,
    extra: 2,
    life_span_years: 3,
    release_date: "2010-12-30",
    volume_size_cm3: 0.46,
  },
  {
    model_name: "VNI-698",
    type: "ai-accelerator",
    material: ["silicon-germanium"],
    processing_power: 8.28,
    cost_to_produce: 22.71,
    extra: 4,
    life_span_years: 14,
    release_date: "2010-03-16",
    volume_size_cm3: 9.75,
  },
  {
    model_name: "YVO-447",
    type: "gpu",
    material: ["silicon-germanium"],
    processing_power: 8.61,
    cost_to_produce: 12.14,
    extra: 4,
    life_span_years: 13,
    release_date: "2018-05-06",
    volume_size_cm3: 1.22,
  },
  {
    model_name: "NGN-361",
    type: "gpu",
    material: ["gallium-arsenide", "gaas", "indium-phosphide"],
    processing_power: 3.01,
    cost_to_produce: 19.68,
    extra: 5,
    life_span_years: 13,
    release_date: "2020-09-07",
    volume_size_cm3: 5.88,
  },
  {
    model_name: "DGR-875",
    type: "fpga",
    material: ["indium-gallium-arsenide"],
    processing_power: 1.12,
    cost_to_produce: 16.82,
    extra: 5,
    life_span_years: 2,
    release_date: "2025-11-13",
    volume_size_cm3: 6.21,
  },
  {
    model_name: "YRZ-536",
    type: "fpga",
    material: ["gan", "inp", "silicon"],
    processing_power: 6.35,
    cost_to_produce: 6.99,
    extra: 5,
    life_span_years: 11,
    release_date: "2007-07-12",
    volume_size_cm3: 4.99,
  },
  {
    model_name: "NNX-161",
    type: "cpu",
    material: ["germanium", "silicon-germanium", "inp"],
    processing_power: 8.21,
    cost_to_produce: 3.14,
    extra: 4,
    life_span_years: 7,
    release_date: "2005-01-31",
    volume_size_cm3: 5.43,
  },
  {
    model_name: "ZFO-182",
    type: "gpu",
    material: ["gaas"],
    processing_power: 8.91,
    cost_to_produce: 6.49,
    extra: 4,
    life_span_years: 12,
    release_date: "1997-03-30",
    volume_size_cm3: 0.52,
  },
  {
    model_name: "VON-493",
    type: "cpu",
    material: ["sige", "gaas"],
    processing_power: 6.94,
    cost_to_produce: 5.1,
    extra: 1,
    life_span_years: 0,
    release_date: "2020-07-21",
    volume_size_cm3: 1.75,
  },
  {
    model_name: "DJE-824",
    type: "gpu",
    material: ["gallium-nitride"],
    processing_power: 9.3,
    cost_to_produce: 17.44,
    extra: 1,
    life_span_years: 13,
    release_date: "2023-05-22",
    volume_size_cm3: 2.18,
  },
  {
    model_name: "ZON-274",
    type: "ai-accelerator",
    material: ["silicon"],
    processing_power: 2.71,
    cost_to_produce: 28.51,
    extra: 1,
    life_span_years: 15,
    release_date: "2020-02-18",
    volume_size_cm3: 5.85,
  },
  {
    model_name: "YIZ-025",
    type: "sensor",
    material: ["germanium"],
    processing_power: 0.66,
    cost_to_produce: 27.89,
    extra: 4,
    life_span_years: 10,
    release_date: "2020-06-20",
    volume_size_cm3: 7.8,
  },
  {
    model_name: "XUY-085",
    type: "ai-accelerator",
    material: ["silicon-germanium", "gallium-nitride"],
    processing_power: 8.82,
    cost_to_produce: 9.59,
    extra: 4,
    life_span_years: 6,
    release_date: "1998-10-16",
    volume_size_cm3: 0.94,
  },
  {
    model_name: "LBD-420",
    type: "fpga",
    material: ["silicon-carbide"],
    processing_power: 0.01,
    cost_to_produce: 25.9,
    extra: 1,
    life_span_years: 5,
    release_date: "2013-01-28",
    volume_size_cm3: 7.5,
  },
  {
    model_name: "LBQ-535",
    type: "ai-accelerator",
    material: ["gan", "gallium-arsenide", "silicon"],
    processing_power: 5.17,
    cost_to_produce: 11.37,
    extra: 1,
    life_span_years: 11,
    release_date: "1995-08-11",
    volume_size_cm3: 7.06,
  },
  {
    model_name: "ACR-984",
    type: "fpga",
    material: ["silicon", "silicon-germanium", "indium-gallium-arsenide"],
    processing_power: 3.92,
    cost_to_produce: 4.38,
    extra: 2,
    life_span_years: 12,
    release_date: "2019-05-26",
    volume_size_cm3: 8.29,
  },
  {
    model_name: "QVS-226",
    type: "sensor",
    material: ["silicon-germanium", "indium-gallium-arsenide"],
    processing_power: 4.62,
    cost_to_produce: 0.95,
    extra: 2,
    life_span_years: 2,
    release_date: "1997-08-20",
    volume_size_cm3: 5.12,
  },
  {
    model_name: "OOY-676",
    type: "ai-accelerator",
    material: ["gaas"],
    processing_power: 0.78,
    cost_to_produce: 13.94,
    extra: 4,
    life_span_years: 1,
    release_date: "2001-07-13",
    volume_size_cm3: 8.94,
  },
  {
    model_name: "FYP-928",
    type: "ai-accelerator",
    material: ["silicon", "silicon-carbide", "gallium-arsenide"],
    processing_power: 4.83,
    cost_to_produce: 23.4,
    extra: 2,
    life_span_years: 12,
    release_date: "2014-09-26",
    volume_size_cm3: 4.61,
  },
  {
    model_name: "WWJ-321",
    type: "controller",
    material: ["indium-phosphide", "indium-gallium-arsenide", "gan"],
    processing_power: 1.59,
    cost_to_produce: 17.44,
    extra: 3,
    life_span_years: 14,
    release_date: "1995-01-24",
    volume_size_cm3: 0.57,
  },
  {
    model_name: "EDM-045",
    type: "fpga",
    material: ["silicon-carbide"],
    processing_power: 3.45,
    cost_to_produce: 21.05,
    extra: 3,
    life_span_years: 13,
    release_date: "2013-07-11",
    volume_size_cm3: 3.75,
  },
  {
    model_name: "XYO-499",
    type: "sensor",
    material: ["indium-gallium-arsenide"],
    processing_power: 6.93,
    cost_to_produce: 29.12,
    extra: 5,
    life_span_years: 1,
    release_date: "2011-02-19",
    volume_size_cm3: 7.04,
  },
  {
    model_name: "QWQ-546",
    type: "cpu",
    material: ["gallium-nitride", "germanium", "silicon-germanium"],
    processing_power: 0.86,
    cost_to_produce: 8.17,
    extra: 3,
    life_span_years: 2,
    release_date: "2012-02-10",
    volume_size_cm3: 8.5,
  },
  {
    model_name: "PVG-254",
    type: "controller",
    material: ["gaas", "germanium"],
    processing_power: 9.78,
    cost_to_produce: 18.22,
    extra: 3,
    life_span_years: 5,
    release_date: "1995-07-30",
    volume_size_cm3: 4.05,
  },
  {
    model_name: "IYJ-769",
    type: "cpu",
    material: ["gallium-nitride"],
    processing_power: 2.68,
    cost_to_produce: 27.4,
    extra: 2,
    life_span_years: 6,
    release_date: "2017-01-09",
    volume_size_cm3: 3.72,
  },
  {
    model_name: "UYV-352",
    type: "ai-accelerator",
    material: ["gallium-arsenide"],
    processing_power: 3.34,
    cost_to_produce: 9.81,
    extra: 1,
    life_span_years: 13,
    release_date: "2011-11-18",
    volume_size_cm3: 0.83,
  },
  {
    model_name: "IXM-770",
    type: "sensor",
    material: ["silicon-carbide", "indium-gallium-arsenide"],
    processing_power: 9.84,
    cost_to_produce: 4.17,
    extra: 1,
    life_span_years: 2,
    release_date: "2011-07-04",
    volume_size_cm3: 4.12,
  },
  {
    model_name: "WPR-097",
    type: "fpga",
    material: ["gallium-nitride", "gan", "sige"],
    processing_power: 7.7,
    cost_to_produce: 22.55,
    extra: 2,
    life_span_years: 9,
    release_date: "2023-02-15",
    volume_size_cm3: 2.0,
  },
  {
    model_name: "OJY-147",
    type: "controller",
    material: ["gaas", "indium-phosphide", "inp"],
    processing_power: 0.02,
    cost_to_produce: 11.13,
    extra: 2,
    life_span_years: 1,
    release_date: "2000-02-13",
    volume_size_cm3: 7.64,
  },
  {
    model_name: "DQK-339",
    type: "cpu",
    material: ["sige", "silicon-germanium", "gaas"],
    processing_power: 1.58,
    cost_to_produce: 8.68,
    extra: 1,
    life_span_years: 0,
    release_date: "2018-05-07",
    volume_size_cm3: 9.44,
  },
  {
    model_name: "CNN-717",
    type: "controller",
    material: ["silicon-carbide", "inp"],
    processing_power: 0.82,
    cost_to_produce: 21.4,
    extra: 4,
    life_span_years: 2,
    release_date: "2003-06-29",
    volume_size_cm3: 1.45,
  },
  {
    model_name: "QYW-414",
    type: "ai-accelerator",
    material: ["silicon-germanium", "silicon"],
    processing_power: 8.11,
    cost_to_produce: 0.52,
    extra: 3,
    life_span_years: 13,
    release_date: "2003-01-10",
    volume_size_cm3: 1.6,
  },
  {
    model_name: "RMT-779",
    type: "gpu",
    material: ["gallium-arsenide", "indium-phosphide", "gallium-nitride"],
    processing_power: 3.83,
    cost_to_produce: 25.58,
    extra: 2,
    life_span_years: 8,
    release_date: "2000-10-20",
    volume_size_cm3: 6.91,
  },
  {
    model_name: "RGC-672",
    type: "gpu",
    material: ["silicon", "gallium-arsenide", "gaas"],
    processing_power: 3.19,
    cost_to_produce: 13.19,
    extra: 5,
    life_span_years: 14,
    release_date: "1997-02-02",
    volume_size_cm3: 1.64,
  },
  {
    model_name: "YOX-895",
    type: "controller",
    material: ["silicon"],
    processing_power: 5.82,
    cost_to_produce: 20.95,
    extra: 3,
    life_span_years: 12,
    release_date: "2020-08-31",
    volume_size_cm3: 3.07,
  },
  {
    model_name: "KIM-514",
    type: "fpga",
    material: ["indium-gallium-arsenide"],
    processing_power: 4.22,
    cost_to_produce: 1.29,
    extra: 4,
    life_span_years: 13,
    release_date: "2005-09-22",
    volume_size_cm3: 8.3,
  },
  {
    model_name: "QTJ-018",
    type: "sensor",
    material: ["gaas", "inp", "indium-phosphide"],
    processing_power: 2.5,
    cost_to_produce: 22.83,
    extra: 4,
    life_span_years: 7,
    release_date: "2001-07-04",
    volume_size_cm3: 7.4,
  },
  {
    model_name: "HFM-173",
    type: "fpga",
    material: ["gallium-nitride", "gaas"],
    processing_power: 3.66,
    cost_to_produce: 4.84,
    extra: 5,
    life_span_years: 7,
    release_date: "2024-01-24",
    volume_size_cm3: 7.05,
  },
  {
    model_name: "FHU-931",
    type: "sensor",
    material: ["germanium", "silicon"],
    processing_power: 2.44,
    cost_to_produce: 10.62,
    extra: 2,
    life_span_years: 9,
    release_date: "1998-09-15",
    volume_size_cm3: 2.2,
  },
  {
    model_name: "BOD-194",
    type: "fpga",
    material: ["gallium-nitride", "gaas"],
    processing_power: 5.95,
    cost_to_produce: 0.48,
    extra: 2,
    life_span_years: 4,
    release_date: "2022-07-07",
    volume_size_cm3: 1.57,
  },
  {
    model_name: "GBG-832",
    type: "sensor",
    material: ["indium-gallium-arsenide", "gallium-arsenide"],
    processing_power: 7.71,
    cost_to_produce: 10.19,
    extra: 3,
    life_span_years: 8,
    release_date: "2021-12-03",
    volume_size_cm3: 3.46,
  },
  {
    model_name: "JSF-518",
    type: "ai-accelerator",
    material: ["inp"],
    processing_power: 5.42,
    cost_to_produce: 29.08,
    extra: 1,
    life_span_years: 12,
    release_date: "2005-07-21",
    volume_size_cm3: 4.13,
  },
  {
    model_name: "CWQ-719",
    type: "cpu",
    material: ["gan", "gallium-nitride", "indium-phosphide"],
    processing_power: 0.63,
    cost_to_produce: 0.55,
    extra: 2,
    life_span_years: 4,
    release_date: "2012-11-09",
    volume_size_cm3: 8.75,
  },
  {
    model_name: "HYO-149",
    type: "controller",
    material: ["inp"],
    processing_power: 3.69,
    cost_to_produce: 8.03,
    extra: 1,
    life_span_years: 9,
    release_date: "2003-04-08",
    volume_size_cm3: 7.17,
  },
  {
    model_name: "WIO-295",
    type: "cpu",
    material: ["gan"],
    processing_power: 7.79,
    cost_to_produce: 28.16,
    extra: 3,
    life_span_years: 1,
    release_date: "2022-06-21",
    volume_size_cm3: 7.2,
  },
  {
    model_name: "KCW-076",
    type: "ai-accelerator",
    material: ["gaas", "silicon-germanium", "silicon-carbide"],
    processing_power: 3.02,
    cost_to_produce: 25.83,
    extra: 4,
    life_span_years: 3,
    release_date: "1997-12-02",
    volume_size_cm3: 7.24,
  },
  {
    model_name: "HFK-705",
    type: "ai-accelerator",
    material: ["gallium-arsenide", "indium-phosphide", "inp"],
    processing_power: 5.59,
    cost_to_produce: 21.71,
    extra: 4,
    life_span_years: 6,
    release_date: "2006-12-13",
    volume_size_cm3: 0.38,
  },
  {
    model_name: "BUX-646",
    type: "cpu",
    material: ["silicon", "germanium", "indium-gallium-arsenide"],
    processing_power: 0.66,
    cost_to_produce: 5.58,
    extra: 2,
    life_span_years: 11,
    release_date: "2025-10-01",
    volume_size_cm3: 5.31,
  },
  {
    model_name: "DFT-111",
    type: "gpu",
    material: ["indium-phosphide", "gallium-arsenide", "gallium-nitride"],
    processing_power: 2.06,
    cost_to_produce: 7.25,
    extra: 4,
    life_span_years: 4,
    release_date: "2018-03-17",
    volume_size_cm3: 2.34,
  },
  {
    model_name: "XVJ-483",
    type: "ai-accelerator",
    material: ["silicon", "gaas"],
    processing_power: 5.64,
    cost_to_produce: 19.51,
    extra: 4,
    life_span_years: 2,
    release_date: "2017-05-16",
    volume_size_cm3: 7.61,
  },
  {
    model_name: "NJG-998",
    type: "gpu",
    material: ["germanium", "gallium-arsenide"],
    processing_power: 6.49,
    cost_to_produce: 14.96,
    extra: 5,
    life_span_years: 5,
    release_date: "2007-03-12",
    volume_size_cm3: 1.79,
  },
  {
    model_name: "VOU-297",
    type: "controller",
    material: [
      "silicon-carbide",
      "indium-gallium-arsenide",
      "indium-phosphide",
    ],
    processing_power: 5.33,
    cost_to_produce: 15.1,
    extra: 2,
    life_span_years: 7,
    release_date: "2014-05-19",
    volume_size_cm3: 2.99,
  },
  {
    model_name: "SFN-428",
    type: "gpu",
    material: ["indium-phosphide", "gan", "gallium-arsenide"],
    processing_power: 3.32,
    cost_to_produce: 12.11,
    extra: 1,
    life_span_years: 2,
    release_date: "1997-08-05",
    volume_size_cm3: 6.77,
  },
  {
    model_name: "BRP-582",
    type: "sensor",
    material: ["silicon-carbide", "gallium-nitride", "sige"],
    processing_power: 7.74,
    cost_to_produce: 6.96,
    extra: 4,
    life_span_years: 1,
    release_date: "2002-04-07",
    volume_size_cm3: 3.98,
  },
  {
    model_name: "EHF-310",
    type: "fpga",
    material: ["indium-gallium-arsenide"],
    processing_power: 7.11,
    cost_to_produce: 7.62,
    extra: 2,
    life_span_years: 5,
    release_date: "2023-03-15",
    volume_size_cm3: 2.4,
  },
  {
    model_name: "XIE-156",
    type: "sensor",
    material: ["inp", "silicon-carbide", "gallium-nitride"],
    processing_power: 1.05,
    cost_to_produce: 21.27,
    extra: 2,
    life_span_years: 13,
    release_date: "1998-02-19",
    volume_size_cm3: 0.15,
  },
  {
    model_name: "KMB-473",
    type: "gpu",
    material: ["sige", "gallium-nitride", "inp"],
    processing_power: 8.71,
    cost_to_produce: 12.36,
    extra: 4,
    life_span_years: 2,
    release_date: "2012-11-27",
    volume_size_cm3: 7.12,
  },
  {
    model_name: "KQV-821",
    type: "controller",
    material: ["gan", "silicon-carbide", "gaas"],
    processing_power: 8.29,
    cost_to_produce: 20.52,
    extra: 5,
    life_span_years: 12,
    release_date: "2010-07-12",
    volume_size_cm3: 3.48,
  },
  {
    model_name: "YVK-237",
    type: "cpu",
    material: ["inp"],
    processing_power: 9.5,
    cost_to_produce: 22.02,
    extra: 4,
    life_span_years: 12,
    release_date: "2008-10-17",
    volume_size_cm3: 5.18,
  },
  {
    model_name: "NMV-885",
    type: "sensor",
    material: ["gaas", "silicon-carbide", "inp"],
    processing_power: 4.16,
    cost_to_produce: 14.85,
    extra: 1,
    life_span_years: 7,
    release_date: "1995-04-21",
    volume_size_cm3: 8.55,
  },
  {
    model_name: "DGN-033",
    type: "ai-accelerator",
    material: ["gaas"],
    processing_power: 6.83,
    cost_to_produce: 12.72,
    extra: 3,
    life_span_years: 0,
    release_date: "1996-03-30",
    volume_size_cm3: 9.22,
  },
  {
    model_name: "IDT-506",
    type: "cpu",
    material: ["germanium"],
    processing_power: 0.55,
    cost_to_produce: 3.38,
    extra: 2,
    life_span_years: 1,
    release_date: "1998-09-29",
    volume_size_cm3: 5.01,
  },
  {
    model_name: "HJG-941",
    type: "gpu",
    material: ["gan", "silicon-carbide", "indium-gallium-arsenide"],
    processing_power: 5.05,
    cost_to_produce: 11.37,
    extra: 2,
    life_span_years: 0,
    release_date: "2016-02-07",
    volume_size_cm3: 5.7,
  },
  {
    model_name: "KZC-947",
    type: "fpga",
    material: ["inp", "silicon"],
    processing_power: 7.78,
    cost_to_produce: 6.72,
    extra: 5,
    life_span_years: 11,
    release_date: "2013-02-08",
    volume_size_cm3: 1.4,
  },
  {
    model_name: "ZGM-367",
    type: "gpu",
    material: ["silicon-carbide", "gan"],
    processing_power: 0.93,
    cost_to_produce: 2.91,
    extra: 1,
    life_span_years: 5,
    release_date: "2002-06-14",
    volume_size_cm3: 2.65,
  },
  {
    model_name: "CWV-800",
    type: "ai-accelerator",
    material: ["indium-gallium-arsenide"],
    processing_power: 1.12,
    cost_to_produce: 20.41,
    extra: 1,
    life_span_years: 12,
    release_date: "1996-12-12",
    volume_size_cm3: 3.11,
  },
  {
    model_name: "YWN-311",
    type: "fpga",
    material: ["inp"],
    processing_power: 4.13,
    cost_to_produce: 5.94,
    extra: 3,
    life_span_years: 11,
    release_date: "2024-04-14",
    volume_size_cm3: 9.37,
  },
  {
    model_name: "LWF-714",
    type: "sensor",
    material: ["silicon"],
    processing_power: 8.89,
    cost_to_produce: 4.26,
    extra: 2,
    life_span_years: 11,
    release_date: "2012-05-08",
    volume_size_cm3: 2.05,
  },
  {
    model_name: "MIY-171",
    type: "controller",
    material: [
      "gallium-arsenide",
      "indium-gallium-arsenide",
      "silicon-carbide",
    ],
    processing_power: 8.13,
    cost_to_produce: 18.53,
    extra: 5,
    life_span_years: 5,
    release_date: "1997-10-08",
    volume_size_cm3: 4.76,
  },
  {
    model_name: "JRO-371",
    type: "gpu",
    material: ["germanium"],
    processing_power: 1.3,
    cost_to_produce: 9.9,
    extra: 1,
    life_span_years: 8,
    release_date: "2022-10-30",
    volume_size_cm3: 8.13,
  },
  {
    model_name: "NQX-721",
    type: "gpu",
    material: ["indium-gallium-arsenide", "gallium-nitride", "silicon"],
    processing_power: 2.86,
    cost_to_produce: 17.73,
    extra: 1,
    life_span_years: 5,
    release_date: "2015-01-06",
    volume_size_cm3: 0.44,
  },
  {
    model_name: "JRM-946",
    type: "cpu",
    material: ["silicon-germanium", "indium-gallium-arsenide"],
    processing_power: 2.51,
    cost_to_produce: 28.86,
    extra: 2,
    life_span_years: 9,
    release_date: "2025-03-21",
    volume_size_cm3: 8.22,
  },
  {
    model_name: "LZK-524",
    type: "ai-accelerator",
    material: ["sige"],
    processing_power: 6.44,
    cost_to_produce: 16.51,
    extra: 4,
    life_span_years: 8,
    release_date: "1997-04-28",
    volume_size_cm3: 3.17,
  },
  {
    model_name: "BEW-014",
    type: "sensor",
    material: ["germanium", "indium-phosphide", "gallium-arsenide"],
    processing_power: 3.52,
    cost_to_produce: 4.2,
    extra: 1,
    life_span_years: 4,
    release_date: "2019-02-03",
    volume_size_cm3: 5.89,
  },
  {
    model_name: "SVF-039",
    type: "ai-accelerator",
    material: ["gallium-arsenide", "gallium-nitride"],
    processing_power: 1.11,
    cost_to_produce: 13.34,
    extra: 1,
    life_span_years: 7,
    release_date: "2025-12-20",
    volume_size_cm3: 7.87,
  },
  {
    model_name: "EJS-969",
    type: "controller",
    material: ["gan", "indium-gallium-arsenide"],
    processing_power: 4.66,
    cost_to_produce: 16.36,
    extra: 5,
    life_span_years: 11,
    release_date: "1996-10-10",
    volume_size_cm3: 4.09,
  },
  {
    model_name: "NGT-314",
    type: "cpu",
    material: ["gaas", "indium-gallium-arsenide", "germanium"],
    processing_power: 3.78,
    cost_to_produce: 11.41,
    extra: 4,
    life_span_years: 1,
    release_date: "2011-09-08",
    volume_size_cm3: 1.09,
  },
  {
    model_name: "OZQ-567",
    type: "cpu",
    material: ["indium-phosphide", "gan"],
    processing_power: 1.76,
    cost_to_produce: 28.08,
    extra: 5,
    life_span_years: 15,
    release_date: "2013-04-08",
    volume_size_cm3: 3.89,
  },
  {
    model_name: "RYV-048",
    type: "cpu",
    material: ["gan", "indium-gallium-arsenide"],
    processing_power: 7.68,
    cost_to_produce: 25.04,
    extra: 3,
    life_span_years: 8,
    release_date: "2024-09-19",
    volume_size_cm3: 5.94,
  },
  {
    model_name: "NIW-578",
    type: "fpga",
    material: ["indium-phosphide", "silicon-germanium", "silicon-carbide"],
    processing_power: 1.36,
    cost_to_produce: 27.13,
    extra: 2,
    life_span_years: 7,
    release_date: "2017-10-31",
    volume_size_cm3: 8.83,
  },
  {
    model_name: "TKA-934",
    type: "gpu",
    material: ["indium-phosphide", "inp"],
    processing_power: 6.84,
    cost_to_produce: 6.67,
    extra: 1,
    life_span_years: 9,
    release_date: "2004-08-06",
    volume_size_cm3: 0.79,
  },
  {
    model_name: "VTC-622",
    type: "ai-accelerator",
    material: ["inp"],
    processing_power: 0.81,
    cost_to_produce: 12.3,
    extra: 2,
    life_span_years: 5,
    release_date: "2003-01-07",
    volume_size_cm3: 4.61,
  },
  {
    model_name: "FNB-687",
    type: "cpu",
    material: [
      "gallium-arsenide",
      "indium-gallium-arsenide",
      "silicon-carbide",
    ],
    processing_power: 0.26,
    cost_to_produce: 12.36,
    extra: 3,
    life_span_years: 2,
    release_date: "2023-01-10",
    volume_size_cm3: 7.91,
  },
  {
    model_name: "BGS-457",
    type: "controller",
    material: ["silicon-germanium"],
    processing_power: 7.34,
    cost_to_produce: 23.59,
    extra: 4,
    life_span_years: 14,
    release_date: "2016-02-03",
    volume_size_cm3: 1.48,
  },
  {
    model_name: "BGG-958",
    type: "cpu",
    material: ["germanium", "inp"],
    processing_power: 6.04,
    cost_to_produce: 6.76,
    extra: 2,
    life_span_years: 11,
    release_date: "2011-09-27",
    volume_size_cm3: 7.33,
  },
  {
    model_name: "LFS-108",
    type: "gpu",
    material: ["gallium-nitride"],
    processing_power: 2.4,
    cost_to_produce: 22.11,
    extra: 1,
    life_span_years: 4,
    release_date: "1998-07-15",
    volume_size_cm3: 6.22,
  },
  {
    model_name: "BPU-691",
    type: "ai-accelerator",
    material: ["silicon-germanium"],
    processing_power: 5.24,
    cost_to_produce: 26.97,
    extra: 3,
    life_span_years: 0,
    release_date: "2012-11-08",
    volume_size_cm3: 4.13,
  },
  {
    model_name: "LZZ-869",
    type: "sensor",
    material: ["gallium-arsenide", "indium-gallium-arsenide"],
    processing_power: 5.73,
    cost_to_produce: 10.2,
    extra: 1,
    life_span_years: 11,
    release_date: "2012-12-20",
    volume_size_cm3: 0.36,
  },
  {
    model_name: "UNC-738",
    type: "sensor",
    material: ["silicon-carbide"],
    processing_power: 5.03,
    cost_to_produce: 7.72,
    extra: 2,
    life_span_years: 1,
    release_date: "2005-07-09",
    volume_size_cm3: 1.12,
  },
  {
    model_name: "NPY-915",
    type: "cpu",
    material: ["indium-phosphide", "gallium-nitride"],
    processing_power: 2.65,
    cost_to_produce: 24.8,
    extra: 5,
    life_span_years: 4,
    release_date: "2011-06-29",
    volume_size_cm3: 2.48,
  },
  {
    model_name: "LUT-303",
    type: "gpu",
    material: ["gallium-arsenide", "silicon-germanium"],
    processing_power: 6.23,
    cost_to_produce: 24.01,
    extra: 5,
    life_span_years: 10,
    release_date: "2004-07-31",
    volume_size_cm3: 9.06,
  },
  {
    model_name: "TBL-883",
    type: "sensor",
    material: ["indium-gallium-arsenide"],
    processing_power: 6.42,
    cost_to_produce: 21.58,
    extra: 1,
    life_span_years: 7,
    release_date: "2022-12-25",
    volume_size_cm3: 8.82,
  },
  {
    model_name: "YXW-667",
    type: "fpga",
    material: ["silicon-carbide"],
    processing_power: 6.28,
    cost_to_produce: 15.32,
    extra: 3,
    life_span_years: 3,
    release_date: "2001-11-10",
    volume_size_cm3: 6.82,
  },
  {
    model_name: "MNE-667",
    type: "gpu",
    material: ["sige", "indium-gallium-arsenide"],
    processing_power: 5.31,
    cost_to_produce: 8.78,
    extra: 1,
    life_span_years: 14,
    release_date: "2013-12-02",
    volume_size_cm3: 1.16,
  },
  {
    model_name: "AZR-371",
    type: "sensor",
    material: ["gaas", "sige"],
    processing_power: 9.02,
    cost_to_produce: 23.2,
    extra: 5,
    life_span_years: 11,
    release_date: "2003-03-09",
    volume_size_cm3: 5.3,
  },
  {
    model_name: "NHT-928",
    type: "fpga",
    material: ["silicon", "inp", "sige"],
    processing_power: 1.29,
    cost_to_produce: 21.74,
    extra: 4,
    life_span_years: 13,
    release_date: "2003-04-04",
    volume_size_cm3: 4.51,
  },
  {
    model_name: "LQB-042",
    type: "fpga",
    material: ["inp", "indium-phosphide"],
    processing_power: 7.26,
    cost_to_produce: 1.35,
    extra: 1,
    life_span_years: 10,
    release_date: "2011-08-09",
    volume_size_cm3: 1.54,
  },
  {
    model_name: "HWM-073",
    type: "fpga",
    material: ["gallium-nitride", "indium-phosphide", "inp"],
    processing_power: 3.43,
    cost_to_produce: 15.63,
    extra: 5,
    life_span_years: 0,
    release_date: "2024-08-29",
    volume_size_cm3: 6.91,
  },
  {
    model_name: "HBK-115",
    type: "fpga",
    material: ["inp"],
    processing_power: 5.15,
    cost_to_produce: 13.94,
    extra: 2,
    life_span_years: 4,
    release_date: "1996-04-22",
    volume_size_cm3: 1.7,
  },
  {
    model_name: "VCW-541",
    type: "fpga",
    material: ["silicon-germanium", "gan", "silicon-carbide"],
    processing_power: 6.86,
    cost_to_produce: 27.93,
    extra: 1,
    life_span_years: 6,
    release_date: "2007-08-07",
    volume_size_cm3: 0.12,
  },
  {
    model_name: "CXU-693",
    type: "gpu",
    material: ["inp"],
    processing_power: 0.35,
    cost_to_produce: 19.22,
    extra: 1,
    life_span_years: 3,
    release_date: "1999-03-01",
    volume_size_cm3: 6.63,
  },
  {
    model_name: "OZQ-430",
    type: "gpu",
    material: ["gallium-nitride", "silicon-germanium", "gaas"],
    processing_power: 6.06,
    cost_to_produce: 23.23,
    extra: 5,
    life_span_years: 2,
    release_date: "2006-07-08",
    volume_size_cm3: 0.69,
  },
  {
    model_name: "WSH-576",
    type: "gpu",
    material: ["silicon-germanium"],
    processing_power: 4.04,
    cost_to_produce: 6.14,
    extra: 5,
    life_span_years: 4,
    release_date: "2024-02-01",
    volume_size_cm3: 0.25,
  },
  {
    model_name: "VKV-178",
    type: "controller",
    material: ["silicon", "indium-gallium-arsenide"],
    processing_power: 0.7,
    cost_to_produce: 17.11,
    extra: 5,
    life_span_years: 2,
    release_date: "2013-05-14",
    volume_size_cm3: 1.32,
  },
  {
    model_name: "MHY-655",
    type: "gpu",
    material: ["indium-gallium-arsenide", "silicon", "gaas"],
    processing_power: 2.28,
    cost_to_produce: 24.34,
    extra: 4,
    life_span_years: 15,
    release_date: "1995-09-26",
    volume_size_cm3: 1.58,
  },
  {
    model_name: "KHY-768",
    type: "controller",
    material: ["germanium", "silicon-germanium"],
    processing_power: 9.78,
    cost_to_produce: 18.58,
    extra: 3,
    life_span_years: 15,
    release_date: "2020-09-09",
    volume_size_cm3: 4.6,
  },
  {
    model_name: "GXX-497",
    type: "gpu",
    material: ["silicon-germanium"],
    processing_power: 7.0,
    cost_to_produce: 27.69,
    extra: 2,
    life_span_years: 7,
    release_date: "2001-03-05",
    volume_size_cm3: 9.57,
  },
  {
    model_name: "KNZ-020",
    type: "sensor",
    material: ["inp"],
    processing_power: 5.54,
    cost_to_produce: 14.69,
    extra: 5,
    life_span_years: 5,
    release_date: "2018-01-01",
    volume_size_cm3: 5.49,
  },
  {
    model_name: "KVV-133",
    type: "ai-accelerator",
    material: ["gallium-nitride"],
    processing_power: 4.32,
    cost_to_produce: 21.61,
    extra: 1,
    life_span_years: 0,
    release_date: "1995-08-29",
    volume_size_cm3: 8.57,
  },
  {
    model_name: "XRK-906",
    type: "controller",
    material: ["indium-phosphide", "gallium-arsenide"],
    processing_power: 6.26,
    cost_to_produce: 19.32,
    extra: 5,
    life_span_years: 13,
    release_date: "2004-03-01",
    volume_size_cm3: 7.06,
  },
  {
    model_name: "VEA-828",
    type: "ai-accelerator",
    material: ["indium-gallium-arsenide"],
    processing_power: 2.33,
    cost_to_produce: 0.49,
    extra: 2,
    life_span_years: 1,
    release_date: "2012-10-14",
    volume_size_cm3: 3.05,
  },
  {
    model_name: "YDF-782",
    type: "sensor",
    material: ["gallium-nitride", "gan", "gaas"],
    processing_power: 3.43,
    cost_to_produce: 23.37,
    extra: 4,
    life_span_years: 11,
    release_date: "2001-09-02",
    volume_size_cm3: 4.07,
  },
  {
    model_name: "ONT-219",
    type: "cpu",
    material: ["indium-gallium-arsenide"],
    processing_power: 3.87,
    cost_to_produce: 6.93,
    extra: 3,
    life_span_years: 2,
    release_date: "1999-10-01",
    volume_size_cm3: 6.35,
  },
  {
    model_name: "AFY-703",
    type: "sensor",
    material: ["sige"],
    processing_power: 3.91,
    cost_to_produce: 16.78,
    extra: 1,
    life_span_years: 11,
    release_date: "1997-06-29",
    volume_size_cm3: 2.47,
  },
  {
    model_name: "XOF-784",
    type: "gpu",
    material: ["silicon", "silicon-germanium", "gaas"],
    processing_power: 4.68,
    cost_to_produce: 22.84,
    extra: 5,
    life_span_years: 6,
    release_date: "1996-05-23",
    volume_size_cm3: 6.51,
  },
  {
    model_name: "HHC-424",
    type: "fpga",
    material: ["inp", "sige"],
    processing_power: 2.28,
    cost_to_produce: 22.56,
    extra: 2,
    life_span_years: 3,
    release_date: "2006-09-21",
    volume_size_cm3: 0.02,
  },
  {
    model_name: "SSD-650",
    type: "gpu",
    material: ["gaas"],
    processing_power: 3.18,
    cost_to_produce: 8.32,
    extra: 5,
    life_span_years: 13,
    release_date: "1995-05-01",
    volume_size_cm3: 2.59,
  },
  {
    model_name: "FXH-455",
    type: "sensor",
    material: ["indium-gallium-arsenide", "inp"],
    processing_power: 0.61,
    cost_to_produce: 10.59,
    extra: 1,
    life_span_years: 2,
    release_date: "2022-05-20",
    volume_size_cm3: 9.42,
  },
  {
    model_name: "USM-488",
    type: "fpga",
    material: ["sige", "gallium-nitride"],
    processing_power: 3.2,
    cost_to_produce: 26.76,
    extra: 4,
    life_span_years: 5,
    release_date: "2010-11-19",
    volume_size_cm3: 6.5,
  },
  {
    model_name: "SJZ-492",
    type: "ai-accelerator",
    material: ["inp"],
    processing_power: 1.12,
    cost_to_produce: 7.88,
    extra: 1,
    life_span_years: 4,
    release_date: "1997-09-06",
    volume_size_cm3: 9.84,
  },
  {
    model_name: "JJO-411",
    type: "gpu",
    material: ["gallium-arsenide", "inp"],
    processing_power: 1.15,
    cost_to_produce: 1.19,
    extra: 3,
    life_span_years: 12,
    release_date: "2001-05-17",
    volume_size_cm3: 8.87,
  },
  {
    model_name: "GKP-237",
    type: "fpga",
    material: ["gallium-nitride", "silicon-carbide"],
    processing_power: 7.03,
    cost_to_produce: 27.88,
    extra: 1,
    life_span_years: 6,
    release_date: "2020-05-09",
    volume_size_cm3: 1.26,
  },
  {
    model_name: "LCO-146",
    type: "cpu",
    material: ["gan", "silicon", "inp"],
    processing_power: 1.34,
    cost_to_produce: 5.93,
    extra: 5,
    life_span_years: 15,
    release_date: "2022-05-22",
    volume_size_cm3: 2.9,
  },
  {
    model_name: "CBL-890",
    type: "gpu",
    material: ["indium-phosphide", "gallium-arsenide"],
    processing_power: 6.82,
    cost_to_produce: 7.68,
    extra: 3,
    life_span_years: 1,
    release_date: "1998-05-09",
    volume_size_cm3: 0.31,
  },
  {
    model_name: "NCY-531",
    type: "cpu",
    material: ["silicon", "gallium-nitride"],
    processing_power: 6.17,
    cost_to_produce: 29.58,
    extra: 4,
    life_span_years: 2,
    release_date: "2020-11-12",
    volume_size_cm3: 8.32,
  },
  {
    model_name: "TOR-510",
    type: "controller",
    material: ["silicon-carbide", "gaas"],
    processing_power: 4.25,
    cost_to_produce: 2.67,
    extra: 2,
    life_span_years: 3,
    release_date: "2014-09-01",
    volume_size_cm3: 4.35,
  },
  {
    model_name: "VPY-927",
    type: "gpu",
    material: ["sige", "gan", "gaas"],
    processing_power: 3.21,
    cost_to_produce: 0.73,
    extra: 5,
    life_span_years: 14,
    release_date: "2005-11-19",
    volume_size_cm3: 5.32,
  },
  {
    model_name: "GVF-743",
    type: "controller",
    material: ["inp"],
    processing_power: 2.86,
    cost_to_produce: 3.0,
    extra: 5,
    life_span_years: 0,
    release_date: "2019-04-17",
    volume_size_cm3: 2.99,
  },
  {
    model_name: "YGY-413",
    type: "ai-accelerator",
    material: ["gallium-arsenide"],
    processing_power: 5.91,
    cost_to_produce: 16.59,
    extra: 1,
    life_span_years: 7,
    release_date: "2025-07-10",
    volume_size_cm3: 8.17,
  },
  {
    model_name: "IQR-187",
    type: "sensor",
    material: ["germanium"],
    processing_power: 4.97,
    cost_to_produce: 0.52,
    extra: 3,
    life_span_years: 2,
    release_date: "2021-03-02",
    volume_size_cm3: 9.45,
  },
  {
    model_name: "YQQ-898",
    type: "ai-accelerator",
    material: ["indium-phosphide", "germanium", "sige"],
    processing_power: 7.12,
    cost_to_produce: 29.74,
    extra: 5,
    life_span_years: 0,
    release_date: "2000-09-05",
    volume_size_cm3: 7.39,
  },
  {
    model_name: "EOM-232",
    type: "fpga",
    material: ["gallium-nitride"],
    processing_power: 5.37,
    cost_to_produce: 20.42,
    extra: 1,
    life_span_years: 6,
    release_date: "2015-10-09",
    volume_size_cm3: 1.49,
  },
  {
    model_name: "RHB-370",
    type: "sensor",
    material: ["gallium-arsenide"],
    processing_power: 9.57,
    cost_to_produce: 1.29,
    extra: 2,
    life_span_years: 10,
    release_date: "2010-05-11",
    volume_size_cm3: 0.06,
  },
  {
    model_name: "SML-437",
    type: "ai-accelerator",
    material: ["silicon", "gaas"],
    processing_power: 1.23,
    cost_to_produce: 29.58,
    extra: 2,
    life_span_years: 1,
    release_date: "2020-08-20",
    volume_size_cm3: 7.29,
  },
  {
    model_name: "ZRV-525",
    type: "fpga",
    material: ["silicon-carbide", "inp"],
    processing_power: 8.05,
    cost_to_produce: 27.96,
    extra: 4,
    life_span_years: 13,
    release_date: "1999-12-16",
    volume_size_cm3: 2.88,
  },
  {
    model_name: "VCW-502",
    type: "controller",
    material: ["sige", "indium-gallium-arsenide"],
    processing_power: 7.05,
    cost_to_produce: 17.72,
    extra: 3,
    life_span_years: 12,
    release_date: "2024-01-23",
    volume_size_cm3: 9.13,
  },
  {
    model_name: "FNU-021",
    type: "gpu",
    material: ["sige", "indium-gallium-arsenide"],
    processing_power: 6.88,
    cost_to_produce: 7.27,
    extra: 5,
    life_span_years: 13,
    release_date: "2006-01-28",
    volume_size_cm3: 7.3,
  },
  {
    model_name: "TIQ-660",
    type: "gpu",
    material: ["silicon-germanium"],
    processing_power: 3.07,
    cost_to_produce: 2.73,
    extra: 1,
    life_span_years: 14,
    release_date: "2012-10-01",
    volume_size_cm3: 6.98,
  },
  {
    model_name: "XMK-629",
    type: "sensor",
    material: ["gan", "inp"],
    processing_power: 9.44,
    cost_to_produce: 29.23,
    extra: 4,
    life_span_years: 9,
    release_date: "2004-06-01",
    volume_size_cm3: 2.09,
  },
  {
    model_name: "WNE-129",
    type: "cpu",
    material: ["silicon-carbide", "silicon-germanium", "gan"],
    processing_power: 4.48,
    cost_to_produce: 12.16,
    extra: 4,
    life_span_years: 4,
    release_date: "2002-08-17",
    volume_size_cm3: 2.61,
  },
  {
    model_name: "PWO-576",
    type: "gpu",
    material: ["germanium", "gaas"],
    processing_power: 8.73,
    cost_to_produce: 5.4,
    extra: 5,
    life_span_years: 12,
    release_date: "1995-03-16",
    volume_size_cm3: 8.07,
  },
  {
    model_name: "XOI-162",
    type: "sensor",
    material: ["gallium-nitride"],
    processing_power: 1.63,
    cost_to_produce: 23.23,
    extra: 5,
    life_span_years: 5,
    release_date: "2021-01-18",
    volume_size_cm3: 6.26,
  },
  {
    model_name: "HOL-385",
    type: "fpga",
    material: ["sige", "silicon-carbide", "indium-phosphide"],
    processing_power: 2.32,
    cost_to_produce: 28.44,
    extra: 5,
    life_span_years: 15,
    release_date: "1996-11-28",
    volume_size_cm3: 4.16,
  },
  {
    model_name: "ULG-694",
    type: "sensor",
    material: ["gallium-arsenide", "silicon", "inp"],
    processing_power: 3.26,
    cost_to_produce: 23.08,
    extra: 1,
    life_span_years: 4,
    release_date: "2002-04-14",
    volume_size_cm3: 8.78,
  },
  {
    model_name: "PUG-392",
    type: "fpga",
    material: ["gallium-arsenide", "germanium", "sige"],
    processing_power: 2.38,
    cost_to_produce: 23.9,
    extra: 2,
    life_span_years: 4,
    release_date: "2017-01-09",
    volume_size_cm3: 5.98,
  },
  {
    model_name: "MND-090",
    type: "ai-accelerator",
    material: ["silicon-carbide", "sige", "silicon-germanium"],
    processing_power: 4.41,
    cost_to_produce: 6.43,
    extra: 3,
    life_span_years: 11,
    release_date: "2013-01-27",
    volume_size_cm3: 9.13,
  },
];
